// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#include "ui_manager.h"
#include "ui_manager_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_manager_init( void )
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main  (LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenLogo_screen_init();
    ui_ScreenMenu_screen_init();
    ui_ScreenDisplayRX_screen_init();
    ui_ScreenLeds_screen_init();
    ui_ScreenDisplayECU_screen_init();
    ui_ScreenDisplayBV_screen_init();
    ui_ScreenRealTime_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr( ui_ScreenLogo);
}

void ui_manager_destroy( void )
{
    ui_ScreenLogo_screen_destroy();
    ui_ScreenMenu_screen_destroy();
    ui_ScreenDisplayRX_screen_destroy();
    ui_ScreenLeds_screen_destroy();
    ui_ScreenDisplayECU_screen_destroy();
    ui_ScreenDisplayBV_screen_destroy();
    ui_ScreenRealTime_screen_destroy();
}
