// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#ifndef _RT_DASH_70_WAVESHARE_ESP32_P4_V1_UI_H
#define _RT_DASH_70_WAVESHARE_ESP32_P4_V1_UI_H

#include "lvgl.h"

typedef enum {
    COLOR_NONE = 0,
    COLOR_GREEN,
    COLOR_ORANGE,
    COLOR_RED,
    COLOR_CYAN,
    COLOR_BLUE
} led_color_t;

//static led_color_t get_color_code_from_img(const void * img_src);
//static const void* get_img_from_color_code(uint32_t code);
void save_global_config_to_nvs(void);
void load_global_config_from_nvs(void);
void check_and_auto_save(void);


void set_target_led(lv_event_t * e);
void reset_led_to_black(lv_event_t * e);
void apply_color_green(lv_event_t * e);
void apply_color_orange(lv_event_t * e);
void apply_color_red(lv_event_t * e);
void apply_color_cyan(lv_event_t * e);
void apply_color_blue(lv_event_t * e);
void set_target_colour(lv_event_t * e);

// Fonctions clavier

void keyboard_backspace(lv_event_t * e);
void keyboard_dot(lv_event_t *e);
void keyboard_0(lv_event_t * e);
void keyboard_1(lv_event_t * e);
void keyboard_2(lv_event_t * e);
void keyboard_3(lv_event_t * e);
void keyboard_4(lv_event_t * e);
void keyboard_5(lv_event_t * e);
void keyboard_6(lv_event_t * e);
void keyboard_7(lv_event_t * e);
void keyboard_8(lv_event_t * e);
void keyboard_9(lv_event_t * e);
void add_key_highlighting(lv_obj_t * obj);
void update_console_display();
void keyboard_add_digit(const char* digit);


#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_manager_helpers.h"
#include "ui_manager_comp.h"
#include "ui_manager_comp_hook.h"
#include "ui_manager_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_ScreenLogo.h"
#include "ui_ScreenMenu.h"
#include "ui_ScreenDisplayRX.h"
#include "ui_ScreenLeds.h"
#include "ui_ScreenDisplayECU.h"
#include "ui_ScreenDisplayBV.h"
#include "ui_ScreenRealTime.h"

///////////////////// VARIABLES ////////////////////

typedef uint32_t ui_style_variable_t;
typedef uint32_t ui_theme_variable_t;

typedef struct {
    ui_theme_variable_t * style_variable_p;
    bool is_themeable;
    void * previous_pointer;
    ui_style_variable_t previous_value;
    uint32_t style_property_setting_count;
    void * style_property_settings; // Pointeur vers la liste chaînée
} _ui_local_style_t;

typedef struct {
    lv_obj_t * object_p;
    lv_style_selector_t selector;
    lv_style_prop_t property;
    void * next_p;
} _ui_local_style_property_setting_t;


// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1764218101 );   // assets/RT_Dash_70_Logo_Loading-01.png
LV_IMG_DECLARE( ui_img_521401086 );   // assets/RT_Dash_70_Menu_waveshare_esp32-p4-01.png
LV_IMG_DECLARE( ui_img_display_png );   // assets/display.png
LV_IMG_DECLARE( ui_img_config_png );   // assets/config.png
LV_IMG_DECLARE( ui_img_leds_png );   // assets/leds.png
LV_IMG_DECLARE( ui_img_realtime_png );   // assets/RealTime.png
LV_IMG_DECLARE( ui_img_gddash_70_fond_png );   // assets/GDDash_70_Fond.png
LV_IMG_DECLARE( ui_img_gauchefond_9000_png );   // assets/GaucheFond_9000.png
LV_IMG_DECLARE( ui_img_gauchecurseur_9000_png );   // assets/GaucheCurseur_9000.png
LV_IMG_DECLARE( ui_img_droitefond_9000_png );   // assets/DroiteFond_9000.png
LV_IMG_DECLARE( ui_img_droitecurseur_9000_png );   // assets/DroiteCurseur_9000.png
LV_IMG_DECLARE( ui_img_btn_menu_png );   // assets/Btn_Menu.png
LV_IMG_DECLARE( ui_img_1968289144 );   // assets/RT_Dash_70_Config_LEDs_waveshare_esp32-p4-01.png
LV_IMG_DECLARE( ui_img_297271254 );   // assets/RT_Dash_70_Config_ECU_Display_waveshare_esp32-p4-01.png
LV_IMG_DECLARE( ui_img_1361701724 );   // assets/CadreRapportBV-05.png
LV_IMG_DECLARE( ui_img_1642545580 );   // assets/RT_Dash_70_RealTime_waveshare_esp32-p4-01.png

// FONTS
LV_FONT_DECLARE( ui_font_RapBV );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic30 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic35 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic40 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic45 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic50 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic55 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic60 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic65 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic75 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic80 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic85 );
LV_FONT_DECLARE( ui_font_VerdanaBoldItalic90 );

// UI INIT
void ui_manager_init(void);
void ui_manager_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
