// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#ifndef _UI_COMP_SLIDER1_H
#define _UI_COMP_SLIDER1_H

#include "../ui_manager.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Slider1
#define UI_COMP_SLIDER1_SLIDER1 0
#define _UI_COMP_SLIDER1_NUM 1
lv_obj_t *ui_Slider1_create(lv_obj_t *comp_parent);
void ui_event_comp_Slider1_Slider1( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
