// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#ifndef UI_SCREENREALTIME_H
#define UI_SCREENREALTIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenRealTime
extern void ui_ScreenRealTime_screen_init(void);
extern void ui_ScreenRealTime_screen_destroy(void);
extern lv_obj_t *ui_ScreenRealTime;
extern lv_obj_t *ui_Horloge4;
extern lv_obj_t *ui_LabelHeure4;
extern lv_obj_t *ui_LabelSepHeureMin4;
extern lv_obj_t *ui_LabelMin4;
extern void ui_event_ButtonHome4( lv_event_t * e);
extern lv_obj_t *ui_ButtonHome4;
extern lv_obj_t *ui_Label3Value2;
extern lv_obj_t *ui_Label3Value3;
extern lv_obj_t *ui_Label3Value4;
extern lv_obj_t *ui_Label3Value5;
extern lv_obj_t *ui_Label3Value6;
extern lv_obj_t *ui_Label3Value7;
extern lv_obj_t *ui_Label3Value8;
extern lv_obj_t *ui_Label3Value9;
extern lv_obj_t *ui_Label3Value10;
extern lv_obj_t *ui_Label3Value11;
extern lv_obj_t *ui_Label3Value12;
extern lv_obj_t *ui_Label3Value13;
extern lv_obj_t *ui_Label3Value14;

// CUSTOM VARIABLES
extern lv_obj_t *uic_Horloge4;
extern lv_obj_t *uic_LabelHeure4;
extern lv_obj_t *uic_LabelSepHeureMin4;
extern lv_obj_t *uic_LabelMin4;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

