// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#include "../ui_manager.h"

lv_obj_t *uic_MenuDisplay9;
lv_obj_t *uic_MenuRealTime8;
lv_obj_t *uic_MenuLeds7;
lv_obj_t *uic_MenuConfig6;
lv_obj_t *uic_MenuDisplay5;
lv_obj_t *uic_MenuRealTime4;
lv_obj_t *uic_MenuLeds3;
lv_obj_t *uic_MenuConfig2;
lv_obj_t *uic_MenuDisplay1;
lv_obj_t *ui_ScreenMenu = NULL;lv_obj_t *ui_MenuDisplay1 = NULL;lv_obj_t *ui_MenuConfig2 = NULL;lv_obj_t *ui_MenuLeds3 = NULL;lv_obj_t *ui_MenuRealTime4 = NULL;lv_obj_t *ui_MenuDisplay5 = NULL;lv_obj_t *ui_MenuConfig6 = NULL;lv_obj_t *ui_MenuLeds7 = NULL;lv_obj_t *ui_MenuRealTime8 = NULL;lv_obj_t *ui_MenuDisplay9 = NULL;
// event funtions
void ui_event_MenuDisplay1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_ScreenDisplayRX, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenDisplayRX_screen_init);
}
}

void ui_event_MenuConfig2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_ScreenDisplayECU, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenDisplayECU_screen_init);
}
}

void ui_event_MenuLeds3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_ScreenLeds, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenLeds_screen_init);
}
}

void ui_event_MenuRealTime4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_ScreenRealTime, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenRealTime_screen_init);
}
}

void ui_event_MenuDisplay5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_ScreenDisplayRX, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenDisplayRX_screen_init);
}
}

void ui_event_MenuConfig6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_ScreenDisplayECU, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenDisplayECU_screen_init);
}
}

void ui_event_MenuLeds7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_ScreenLeds, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenLeds_screen_init);
}
}

void ui_event_MenuRealTime8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_ScreenRealTime, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenRealTime_screen_init);
}
}

void ui_event_MenuDisplay9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_ScreenDisplayRX, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenDisplayRX_screen_init);
}
}

// build funtions

void ui_ScreenMenu_screen_init(void)
{
ui_ScreenMenu = lv_obj_create(NULL);
lv_obj_add_flag( ui_ScreenMenu, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_set_scrollbar_mode(ui_ScreenMenu, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_ScreenMenu, LV_DIR_HOR);
lv_obj_set_scroll_snap_x(ui_ScreenMenu, LV_SCROLL_SNAP_CENTER);
lv_obj_set_style_bg_img_src( ui_ScreenMenu, &ui_img_521401086, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_MenuDisplay1 = lv_obj_create(ui_ScreenMenu);
lv_obj_set_width( ui_MenuDisplay1, 441);
lv_obj_set_height( ui_MenuDisplay1, 202);
lv_obj_set_y( ui_MenuDisplay1, 0 );
lv_obj_set_x( ui_MenuDisplay1, lv_pct(-200) );
lv_obj_set_align( ui_MenuDisplay1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuDisplay1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuDisplay1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_MenuDisplay1, lv_color_hex(0xF6FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuDisplay1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MenuDisplay1, &ui_img_display_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_MenuDisplay1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MenuDisplay1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuConfig2 = lv_obj_create(ui_ScreenMenu);
lv_obj_set_width( ui_MenuConfig2, 441);
lv_obj_set_height( ui_MenuConfig2, 202);
lv_obj_set_y( ui_MenuConfig2, 0 );
lv_obj_set_x( ui_MenuConfig2, lv_pct(-150) );
lv_obj_set_align( ui_MenuConfig2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuConfig2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuConfig2, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_MenuConfig2, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuConfig2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MenuConfig2, &ui_img_config_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_MenuConfig2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MenuConfig2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuLeds3 = lv_obj_create(ui_ScreenMenu);
lv_obj_set_width( ui_MenuLeds3, 441);
lv_obj_set_height( ui_MenuLeds3, 202);
lv_obj_set_y( ui_MenuLeds3, 0 );
lv_obj_set_x( ui_MenuLeds3, lv_pct(-100) );
lv_obj_set_align( ui_MenuLeds3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuLeds3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuLeds3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_MenuLeds3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuLeds3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MenuLeds3, &ui_img_leds_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_MenuLeds3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MenuLeds3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuRealTime4 = lv_obj_create(ui_ScreenMenu);
lv_obj_set_width( ui_MenuRealTime4, 441);
lv_obj_set_height( ui_MenuRealTime4, 202);
lv_obj_set_y( ui_MenuRealTime4, 0 );
lv_obj_set_x( ui_MenuRealTime4, lv_pct(-50) );
lv_obj_set_align( ui_MenuRealTime4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuRealTime4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuRealTime4, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_MenuRealTime4, lv_color_hex(0xE300FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuRealTime4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MenuRealTime4, &ui_img_realtime_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_MenuRealTime4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MenuRealTime4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuDisplay5 = lv_obj_create(ui_ScreenMenu);
lv_obj_set_width( ui_MenuDisplay5, 441);
lv_obj_set_height( ui_MenuDisplay5, 202);
lv_obj_set_align( ui_MenuDisplay5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuDisplay5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuDisplay5, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_radius(ui_MenuDisplay5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MenuDisplay5, lv_color_hex(0xF6FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuDisplay5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MenuDisplay5, &ui_img_display_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_MenuDisplay5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MenuDisplay5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuConfig6 = lv_obj_create(ui_ScreenMenu);
lv_obj_set_width( ui_MenuConfig6, 441);
lv_obj_set_height( ui_MenuConfig6, 202);
lv_obj_set_y( ui_MenuConfig6, 0 );
lv_obj_set_x( ui_MenuConfig6, lv_pct(50) );
lv_obj_set_align( ui_MenuConfig6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuConfig6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuConfig6, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_snap_x(ui_MenuConfig6, LV_SCROLL_SNAP_CENTER);
lv_obj_set_style_bg_color(ui_MenuConfig6, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuConfig6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MenuConfig6, &ui_img_config_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_MenuConfig6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MenuConfig6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuLeds7 = lv_obj_create(ui_ScreenMenu);
lv_obj_set_width( ui_MenuLeds7, 441);
lv_obj_set_height( ui_MenuLeds7, 202);
lv_obj_set_y( ui_MenuLeds7, 0 );
lv_obj_set_x( ui_MenuLeds7, lv_pct(100) );
lv_obj_set_align( ui_MenuLeds7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuLeds7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuLeds7, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_MenuLeds7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuLeds7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MenuLeds7, &ui_img_leds_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_MenuLeds7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MenuLeds7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuRealTime8 = lv_obj_create(ui_ScreenMenu);
lv_obj_set_width( ui_MenuRealTime8, 441);
lv_obj_set_height( ui_MenuRealTime8, 202);
lv_obj_set_y( ui_MenuRealTime8, 0 );
lv_obj_set_x( ui_MenuRealTime8, lv_pct(150) );
lv_obj_set_align( ui_MenuRealTime8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuRealTime8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuRealTime8, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scroll_dir(ui_MenuRealTime8, LV_DIR_HOR);
lv_obj_set_style_bg_color(ui_MenuRealTime8, lv_color_hex(0xE300FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuRealTime8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MenuRealTime8, &ui_img_realtime_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_MenuRealTime8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MenuRealTime8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuDisplay9 = lv_obj_create(ui_ScreenMenu);
lv_obj_set_width( ui_MenuDisplay9, 441);
lv_obj_set_height( ui_MenuDisplay9, 202);
lv_obj_set_y( ui_MenuDisplay9, 0 );
lv_obj_set_x( ui_MenuDisplay9, lv_pct(200) );
lv_obj_set_align( ui_MenuDisplay9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuDisplay9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuDisplay9, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_MenuDisplay9, lv_color_hex(0xF6FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuDisplay9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MenuDisplay9, &ui_img_display_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_MenuDisplay9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MenuDisplay9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_MenuDisplay1, ui_event_MenuDisplay1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MenuConfig2, ui_event_MenuConfig2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MenuLeds3, ui_event_MenuLeds3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MenuRealTime4, ui_event_MenuRealTime4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MenuDisplay5, ui_event_MenuDisplay5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MenuConfig6, ui_event_MenuConfig6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MenuLeds7, ui_event_MenuLeds7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MenuRealTime8, ui_event_MenuRealTime8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MenuDisplay9, ui_event_MenuDisplay9, LV_EVENT_ALL, NULL);
uic_MenuDisplay1 = ui_MenuDisplay1;
uic_MenuConfig2 = ui_MenuConfig2;
uic_MenuLeds3 = ui_MenuLeds3;
uic_MenuRealTime4 = ui_MenuRealTime4;
uic_MenuDisplay5 = ui_MenuDisplay5;
uic_MenuConfig6 = ui_MenuConfig6;
uic_MenuLeds7 = ui_MenuLeds7;
uic_MenuRealTime8 = ui_MenuRealTime8;
uic_MenuDisplay9 = ui_MenuDisplay9;

}

void ui_ScreenMenu_screen_destroy(void)
{
   if (ui_ScreenMenu) lv_obj_del(ui_ScreenMenu);

// NULL screen variables
ui_ScreenMenu= NULL;
uic_MenuDisplay1= NULL;
ui_MenuDisplay1= NULL;
uic_MenuConfig2= NULL;
ui_MenuConfig2= NULL;
uic_MenuLeds3= NULL;
ui_MenuLeds3= NULL;
uic_MenuRealTime4= NULL;
ui_MenuRealTime4= NULL;
uic_MenuDisplay5= NULL;
ui_MenuDisplay5= NULL;
uic_MenuConfig6= NULL;
ui_MenuConfig6= NULL;
uic_MenuLeds7= NULL;
ui_MenuLeds7= NULL;
uic_MenuRealTime8= NULL;
ui_MenuRealTime8= NULL;
uic_MenuDisplay9= NULL;
ui_MenuDisplay9= NULL;

}
