// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#include "../ui_manager.h"

extern const lv_img_dsc_t ui_img_bouton_vert_png;
extern const lv_img_dsc_t ui_img_bouton_orange_png;
extern const lv_img_dsc_t ui_img_bouton_rouge_png;
extern const lv_img_dsc_t ui_img_bouton_cyan_png;
extern const lv_img_dsc_t ui_img_bouton_bleu_png;
extern const lv_img_dsc_t ui_img_bouton_noir_png;

lv_obj_t *uic_keydot;
lv_obj_t *uic_key0;
lv_obj_t *uic_keybackspace;
lv_obj_t *uic_key9;
lv_obj_t *uic_key8;
lv_obj_t *uic_key7;
lv_obj_t *uic_key6;
lv_obj_t *uic_key5;
lv_obj_t *uic_key4;
lv_obj_t *uic_key3;
lv_obj_t *uic_key2;
lv_obj_t *uic_key1;
lv_obj_t *uic_console_label;


lv_obj_t *uic_LabelMin2;
lv_obj_t *uic_LabelSepHeureMin2;
lv_obj_t *uic_LabelHeure2;
lv_obj_t *uic_Horloge2;
lv_obj_t *uic_ButtonHome2;
lv_obj_t *uic_LabelTeauMax;
lv_obj_t *uic_LabelRPMOilMini;
lv_obj_t *uic_LabelPoilMini;
lv_obj_t *uic_LabelShiftMax2;
lv_obj_t *uic_LabelShiftMax1;
lv_obj_t *uic_LabelShift8;
lv_obj_t *uic_LabelShift7;
lv_obj_t *uic_LabelShift6;
lv_obj_t *uic_LabelShift5;
lv_obj_t *uic_LabelShift4;
lv_obj_t *uic_LabelShift3;
lv_obj_t *uic_LabelShift2;
lv_obj_t *uic_LabelShift1;

lv_obj_t *uic_PanelShift1;
lv_obj_t *uic_PanelShift2 = NULL;
lv_obj_t *uic_PanelShift3 = NULL;
lv_obj_t *uic_PanelShift4 = NULL;
lv_obj_t *uic_PanelShift5 = NULL;
lv_obj_t *uic_PanelShift6 = NULL;
lv_obj_t *uic_PanelShift7 = NULL;
lv_obj_t *uic_PanelShift8 = NULL;

lv_obj_t *uic_PanelShiftMaxi1 = NULL;
lv_obj_t *uic_PanelShiftMaxi2 = NULL;
lv_obj_t *uic_PanelShiftMaxi3 = NULL;
lv_obj_t *uic_PanelShiftMaxi4 = NULL;
lv_obj_t *uic_PanelShiftMaxi5 = NULL;
lv_obj_t *uic_PanelPOil = NULL;
lv_obj_t *uic_PanelTempWater = NULL;

lv_obj_t *uic_greenledpanel = NULL;
lv_obj_t *uic_orangeledpanel = NULL;
lv_obj_t *uic_redledpanel = NULL;
lv_obj_t *uic_cyanledpanel = NULL;
lv_obj_t *uic_blueledpanel = NULL;

lv_obj_t *ui_ScreenLeds = NULL;
lv_obj_t *ui_PanelShift1 = NULL;
lv_obj_t *ui_PanelShift2 = NULL;
lv_obj_t *ui_PanelShift3 = NULL;
lv_obj_t *ui_PanelShift4 = NULL;
lv_obj_t *ui_PanelShift5 = NULL;
lv_obj_t *ui_PanelShift6 = NULL;
lv_obj_t *ui_PanelShift7 = NULL;
lv_obj_t *ui_PanelShift8 = NULL;

lv_obj_t *ui_PanelShiftMaxi1 = NULL;
lv_obj_t *ui_PanelShiftMaxi2 = NULL;
lv_obj_t *ui_PanelShiftMaxi3 = NULL;
lv_obj_t *ui_PanelShiftMaxi4 = NULL;
lv_obj_t *ui_PanelShiftMaxi5 = NULL;
lv_obj_t *ui_PanelPOil = NULL;
lv_obj_t *ui_PanelTempWater = NULL;

lv_obj_t *ui_greenledpanel = NULL;
lv_obj_t *ui_orangeledpanel = NULL;
lv_obj_t *ui_redledpanel = NULL;
lv_obj_t *ui_cyanledpanel = NULL;
lv_obj_t *ui_blueledpanel = NULL;

lv_obj_t *ui_LabelShift1 = NULL;
lv_obj_t *ui_LabelShift2 = NULL;
lv_obj_t *ui_LabelShift3 = NULL;
lv_obj_t *ui_LabelShift4 = NULL;
lv_obj_t *ui_LabelShift5 = NULL;
lv_obj_t *ui_LabelShift6 = NULL;
lv_obj_t *ui_LabelShift7 = NULL;
lv_obj_t *ui_LabelShift8 = NULL;
lv_obj_t *ui_LabelShiftMax1 = NULL;
lv_obj_t *ui_LabelShiftMax2 = NULL;
lv_obj_t *ui_LabelPoilMini = NULL;
lv_obj_t *ui_LabelRPMOilMini = NULL;
lv_obj_t *ui_LabelTeauMax = NULL;
lv_obj_t *ui_ButtonHome2 = NULL;
lv_obj_t *ui_Horloge2 = NULL;
lv_obj_t *ui_LabelHeure2 = NULL;
lv_obj_t *ui_LabelSepHeureMin2 = NULL;
lv_obj_t *ui_LabelMin2 = NULL;


lv_obj_t *ui_console_label = NULL;
lv_obj_t *ui_key1 = NULL;
lv_obj_t *ui_key2 = NULL;
lv_obj_t *ui_key3 = NULL;
lv_obj_t *ui_key4 = NULL;
lv_obj_t *ui_key5 = NULL;
lv_obj_t *ui_key6 = NULL;
lv_obj_t *ui_key7 = NULL;
lv_obj_t *ui_key8 = NULL;
lv_obj_t *ui_key9 = NULL;
lv_obj_t *ui_keybackspace = NULL;
lv_obj_t *ui_key0 = NULL;
lv_obj_t *ui_keydot = NULL;



// event funtions
void ui_event_ScreenLeds( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) 
    {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change( &ui_ScreenDisplayECU, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenDisplayECU_screen_init);
    }
}

// event funtions
void ui_event_PanelShift1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}

void ui_event_PanelShift2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}


void ui_event_PanelShift3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}

void ui_event_PanelShift4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}


void ui_event_PanelShift5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}


void ui_event_PanelShift6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}


void ui_event_PanelShift7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}


void ui_event_PanelShift8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}

void ui_event_PanelShiftMaxi1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}


void ui_event_PanelShiftMaxi2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}

void ui_event_PanelShiftMaxi3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}

void ui_event_PanelShiftMaxi4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}

void ui_event_PanelShiftMaxi5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}


void ui_event_PanelPOil( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}


void ui_event_PanelTempWater( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        set_target_led( e );
    }

    if ( event_code == LV_EVENT_CLICKED) 
    {
        reset_led_to_black( e );
    }
}


void ui_event_greenledpanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        apply_color_green( e );
    }
}

void ui_event_orangeledpanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        apply_color_orange( e );
    }
}

void ui_event_redledpanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        apply_color_red( e );
    }
}

void ui_event_cyanledpanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        apply_color_cyan( e );
    }
}

void ui_event_blueledpanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        apply_color_blue( e );
    }
}


void ui_event_ButtonHome2( lv_event_t * e) 
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) {
        _ui_screen_change( &ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMenu_screen_init);
    }
}


void ui_event_key1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED)
    {
        keyboard_1( e );
    }
}

void ui_event_key2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_2( e );
    }
}

void ui_event_key3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_3( e );
    }
}

void ui_event_key4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_4( e );
    }
}

void ui_event_key5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_5( e );
    }
}

void ui_event_key6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_6( e );
    }
}

void ui_event_key7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_7( e );
    }
}

void ui_event_key8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_8( e );
    }
}

void ui_event_key9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_9( e );
    }
}

void ui_event_keybackspace( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_backspace( e );
    }
}

void ui_event_key0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_0( e );
    }
}

void ui_event_keydot( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) 
    {
        keyboard_dot( e );
    }
}


// build funtions

void ui_ScreenLeds_screen_init(void)
{
    ui_ScreenLeds = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_ScreenLeds, LV_OBJ_FLAG_SCROLLABLE );    
    lv_obj_set_style_bg_img_src( ui_ScreenLeds, &ui_img_1968289144, LV_PART_MAIN | LV_STATE_DEFAULT );


    ui_PanelShift1 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width(ui_PanelShift1, 76);
    lv_obj_set_height(ui_PanelShift1, 76);
    lv_obj_set_x(ui_PanelShift1, -448);
    lv_obj_set_y(ui_PanelShift1, -146);
    lv_obj_set_align(ui_PanelShift1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelShift1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_img_src( ui_PanelShift1, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_radius(ui_PanelShift1, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShift1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShift1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShift1, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShift1, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShift1, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShift1, 255, LV_PART_MAIN | LV_STATE_CHECKED);


    ui_PanelShift2 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShift2, 76);
    lv_obj_set_height( ui_PanelShift2, 76);
    lv_obj_set_x( ui_PanelShift2, -328 );
    lv_obj_set_y( ui_PanelShift2, -146 );
    lv_obj_set_align( ui_PanelShift2, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShift2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShift2, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_PanelShift2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_PanelShift2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PanelShift2, 255, LV_PART_MAIN | LV_STATE_DEFAULT); // Changé à 255
    lv_obj_set_style_opa(ui_PanelShift2, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_radius(ui_PanelShift2, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShift2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelShift2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShift2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShift2, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShift2, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShift2, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShift2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelShift3 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShift3, 76);
    lv_obj_set_height( ui_PanelShift3, 76);
    lv_obj_set_x( ui_PanelShift3, -209 );
    lv_obj_set_y( ui_PanelShift3, -146 );
    lv_obj_set_align( ui_PanelShift3, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShift3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShift3, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_PanelShift3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_PanelShift3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PanelShift3, 255, LV_PART_MAIN | LV_STATE_DEFAULT); // Changé à 255
    lv_obj_set_style_opa(ui_PanelShift3, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_radius(ui_PanelShift3, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShift3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelShift3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShift3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShift3, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShift3, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShift3, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShift3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelShift4 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShift4, 76);
    lv_obj_set_height( ui_PanelShift4, 76);
    lv_obj_set_x( ui_PanelShift4, -89 );
    lv_obj_set_y( ui_PanelShift4, -146 );
    lv_obj_set_align( ui_PanelShift4, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShift4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShift4, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_PanelShift4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_PanelShift4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PanelShift4, 255, LV_PART_MAIN | LV_STATE_DEFAULT); // Changé à 255
    lv_obj_set_style_opa(ui_PanelShift4, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_radius(ui_PanelShift4, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShift4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelShift4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShift4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShift4, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShift4, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShift4, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShift4, 255, LV_PART_MAIN | LV_STATE_CHECKED);


    ui_PanelShift5 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShift5, 76);
    lv_obj_set_height( ui_PanelShift5, 76);
    lv_obj_set_x( ui_PanelShift5, 31 );
    lv_obj_set_y( ui_PanelShift5, -146 );
    lv_obj_set_align( ui_PanelShift5, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShift5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShift5, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_PanelShift5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_PanelShift5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PanelShift5, 255, LV_PART_MAIN | LV_STATE_DEFAULT); // Changé à 255
    lv_obj_set_style_opa(ui_PanelShift5, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_radius(ui_PanelShift5, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShift5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelShift5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShift5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShift5, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShift5, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShift5, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShift5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelShift6 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShift6, 76);
    lv_obj_set_height( ui_PanelShift6, 76);
    lv_obj_set_x( ui_PanelShift6, 150 );
    lv_obj_set_y( ui_PanelShift6, -146 );
    lv_obj_set_align( ui_PanelShift6, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShift6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShift6, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_PanelShift6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_PanelShift6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PanelShift6, 255, LV_PART_MAIN | LV_STATE_DEFAULT); // Changé à 255
    lv_obj_set_style_opa(ui_PanelShift6, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_radius(ui_PanelShift6, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShift6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelShift6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShift6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShift6, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShift6, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShift6, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShift6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelShift7 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShift7, 76);
    lv_obj_set_height( ui_PanelShift7, 76);
    lv_obj_set_x( ui_PanelShift7, 270 );
    lv_obj_set_y( ui_PanelShift7, -146 );
    lv_obj_set_align( ui_PanelShift7, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShift7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShift7, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_PanelShift7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_PanelShift7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PanelShift7, 255, LV_PART_MAIN | LV_STATE_DEFAULT); // Changé à 255
    lv_obj_set_style_opa(ui_PanelShift7, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_radius(ui_PanelShift7, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShift7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelShift7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShift7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShift7, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShift7, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShift7, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShift7, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelShift8 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShift8, 76);
    lv_obj_set_height( ui_PanelShift8, 76);
    lv_obj_set_x( ui_PanelShift8, 389 );
    lv_obj_set_y( ui_PanelShift8, -146 );
    lv_obj_set_align( ui_PanelShift8, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShift8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShift8, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_PanelShift8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_PanelShift8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PanelShift8, 255, LV_PART_MAIN | LV_STATE_DEFAULT); // Changé à 255
    lv_obj_set_style_opa(ui_PanelShift8, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_radius(ui_PanelShift8, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShift8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelShift8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShift8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShift8, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShift8, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShift8, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShift8, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelShiftMaxi1 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShiftMaxi1, 76);
    lv_obj_set_height( ui_PanelShiftMaxi1, 76);
    lv_obj_set_x( ui_PanelShiftMaxi1, -443 );
    lv_obj_set_y( ui_PanelShiftMaxi1, 18 );
    lv_obj_set_align( ui_PanelShiftMaxi1, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShiftMaxi1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShiftMaxi1, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_radius(ui_PanelShiftMaxi1, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShiftMaxi1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShiftMaxi1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShiftMaxi1, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShiftMaxi1, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShiftMaxi1, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShiftMaxi1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelShiftMaxi2 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShiftMaxi2, 76);
    lv_obj_set_height( ui_PanelShiftMaxi2, 76);
    lv_obj_set_x( ui_PanelShiftMaxi2, -314 );
    lv_obj_set_y( ui_PanelShiftMaxi2, 17 );
    lv_obj_set_align( ui_PanelShiftMaxi2, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShiftMaxi2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShiftMaxi2, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_radius(ui_PanelShiftMaxi2, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShiftMaxi2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShiftMaxi2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShiftMaxi2, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShiftMaxi2, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShiftMaxi2, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShiftMaxi2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelShiftMaxi3 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShiftMaxi3, 76);
    lv_obj_set_height( ui_PanelShiftMaxi3, 76);
    lv_obj_set_x( ui_PanelShiftMaxi3, -185 );
    lv_obj_set_y( ui_PanelShiftMaxi3, 17 );
    lv_obj_set_align( ui_PanelShiftMaxi3, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShiftMaxi3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShiftMaxi3, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_radius(ui_PanelShiftMaxi3, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShiftMaxi3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShiftMaxi3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShiftMaxi3, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShiftMaxi3, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShiftMaxi3, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShiftMaxi3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelShiftMaxi4 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShiftMaxi4, 76);
    lv_obj_set_height( ui_PanelShiftMaxi4, 76);
    lv_obj_set_x( ui_PanelShiftMaxi4, -56 );
    lv_obj_set_y( ui_PanelShiftMaxi4, 17 );
    lv_obj_set_align( ui_PanelShiftMaxi4, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShiftMaxi4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShiftMaxi4, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_radius(ui_PanelShiftMaxi4, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShiftMaxi4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShiftMaxi4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShiftMaxi4, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShiftMaxi4, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShiftMaxi4, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShiftMaxi4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelShiftMaxi5 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelShiftMaxi5, 76);
    lv_obj_set_height( ui_PanelShiftMaxi5, 76);
    lv_obj_set_x( ui_PanelShiftMaxi5, 74 );
    lv_obj_set_y( ui_PanelShiftMaxi5, 17 );
    lv_obj_set_align( ui_PanelShiftMaxi5, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelShiftMaxi5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelShiftMaxi5, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_radius(ui_PanelShiftMaxi5, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelShiftMaxi5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelShiftMaxi5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelShiftMaxi5, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelShiftMaxi5, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelShiftMaxi5, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelShiftMaxi5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelPOil = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelPOil, 76);
    lv_obj_set_height( ui_PanelPOil, 76);
    lv_obj_set_x( ui_PanelPOil, -448 );
    lv_obj_set_y( ui_PanelPOil, 233 );
    lv_obj_set_align( ui_PanelPOil, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelPOil, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelPOil, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_radius(ui_PanelPOil, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelPOil, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPOil, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelPOil, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelPOil, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelPOil, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelPOil, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelTempWater = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_PanelTempWater, 76);
    lv_obj_set_height( ui_PanelTempWater, 76);
    lv_obj_set_x( ui_PanelTempWater, -65 );
    lv_obj_set_y( ui_PanelTempWater, 233 );
    lv_obj_set_align( ui_PanelTempWater, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_PanelTempWater, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_PanelTempWater, &ui_img_bouton_noir_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_radius(ui_PanelTempWater, 50, LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_border_width(ui_PanelTempWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTempWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelTempWater, lv_color_hex(0x00FFC7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PanelTempWater, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PanelTempWater, 10, LV_PART_MAIN | LV_STATE_CHECKED);  
    lv_obj_set_style_shadow_opa(ui_PanelTempWater, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_greenledpanel = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_greenledpanel, 58);
    lv_obj_set_height( ui_greenledpanel, 58);
    lv_obj_set_x( ui_greenledpanel, 427 );
    lv_obj_set_y( ui_greenledpanel, 2 );
    lv_obj_set_align( ui_greenledpanel, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_greenledpanel, LV_OBJ_FLAG_SCROLLABLE );    
    lv_obj_set_style_radius(ui_greenledpanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src( ui_greenledpanel, &ui_img_bouton_vert_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_img_opa(ui_greenledpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_greenledpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_orangeledpanel = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_orangeledpanel, 58);
    lv_obj_set_height( ui_orangeledpanel, 58);
    lv_obj_set_x( ui_orangeledpanel, 426 );
    lv_obj_set_y( ui_orangeledpanel, 63 );
    lv_obj_set_align( ui_orangeledpanel, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_orangeledpanel, LV_OBJ_FLAG_SCROLLABLE );    
    lv_obj_set_style_radius(ui_orangeledpanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src( ui_orangeledpanel, &ui_img_bouton_orange_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_img_opa(ui_orangeledpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_orangeledpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_outline_opa(ui_orangeledpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_orangeledpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


    ui_redledpanel = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_redledpanel, 58);
    lv_obj_set_height( ui_redledpanel, 58);
    lv_obj_set_x( ui_redledpanel, 428 );
    lv_obj_set_y( ui_redledpanel, 124 );
    lv_obj_set_align( ui_redledpanel, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_redledpanel, LV_OBJ_FLAG_SCROLLABLE );   
    lv_obj_set_style_radius(ui_redledpanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src( ui_redledpanel, &ui_img_bouton_rouge_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_img_opa(ui_redledpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_redledpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_outline_opa(ui_redledpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_redledpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


    ui_cyanledpanel = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_cyanledpanel, 58);
    lv_obj_set_height( ui_cyanledpanel, 58);
    lv_obj_set_x( ui_cyanledpanel, 427 );
    lv_obj_set_y( ui_cyanledpanel, 186 );
    lv_obj_set_align( ui_cyanledpanel, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_cyanledpanel, LV_OBJ_FLAG_SCROLLABLE );   
    lv_obj_set_style_radius(ui_cyanledpanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src( ui_cyanledpanel, &ui_img_bouton_cyan_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_img_opa(ui_cyanledpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_cyanledpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_outline_opa(ui_cyanledpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_cyanledpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


    ui_blueledpanel = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_blueledpanel, 58);
    lv_obj_set_height( ui_blueledpanel, 58);
    lv_obj_set_x( ui_blueledpanel, 427 );
    lv_obj_set_y( ui_blueledpanel, 249 );
    lv_obj_set_align( ui_blueledpanel, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_blueledpanel, LV_OBJ_FLAG_SCROLLABLE );   
    lv_obj_set_style_radius(ui_blueledpanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src( ui_blueledpanel, &ui_img_bouton_bleu_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_img_opa(ui_blueledpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_blueledpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_outline_opa(ui_blueledpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_blueledpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



    ui_LabelShift1 = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelShift1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelShift1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelShift1, 20 );
    lv_obj_set_y( ui_LabelShift1, 195 );
    lv_label_set_text(ui_LabelShift1,"7500");
    lv_obj_set_style_text_color(ui_LabelShift1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelShift1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShift1, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelShift2 = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelShift2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelShift2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelShift2, 136 );
    lv_obj_set_y( ui_LabelShift2, 195 );
    lv_label_set_text(ui_LabelShift2,"7500");
    lv_obj_set_style_text_color(ui_LabelShift2, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelShift2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShift2, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelShift3 = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelShift3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelShift3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelShift3, 258 );
    lv_obj_set_y( ui_LabelShift3, 195 );
    lv_label_set_text(ui_LabelShift3,"7500");
    lv_obj_set_style_text_color(ui_LabelShift3, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelShift3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShift3, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelShift4 = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelShift4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelShift4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelShift4, 379 );
    lv_obj_set_y( ui_LabelShift4, 195 );
    lv_label_set_text(ui_LabelShift4,"7500");
    lv_obj_set_style_text_color(ui_LabelShift4, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelShift4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShift4, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelShift5 = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelShift5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelShift5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelShift5, 499 );
    lv_obj_set_y( ui_LabelShift5, 195 );
    lv_label_set_text(ui_LabelShift5,"7500");
    lv_obj_set_style_text_color(ui_LabelShift5, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelShift5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShift5, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelShift6 = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelShift6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelShift6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelShift6, 619 );
    lv_obj_set_y( ui_LabelShift6, 195 );
    lv_label_set_text(ui_LabelShift6,"7500");
    lv_obj_set_style_text_color(ui_LabelShift6, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelShift6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShift6, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelShift7 = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelShift7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelShift7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelShift7, 738 );
    lv_obj_set_y( ui_LabelShift7, 195 );
    lv_label_set_text(ui_LabelShift7,"7500");
    lv_obj_set_style_text_color(ui_LabelShift7, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelShift7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShift7, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelShift8 = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelShift8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelShift8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelShift8, 857 );
    lv_obj_set_y( ui_LabelShift8, 195 );
    lv_label_set_text(ui_LabelShift8,"7500");
    lv_obj_set_style_text_color(ui_LabelShift8, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelShift8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShift8, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelShiftMax1 = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelShiftMax1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelShiftMax1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelShiftMax1, 26 );
    lv_obj_set_y( ui_LabelShiftMax1, 360 );
    lv_label_set_text(ui_LabelShiftMax1,"7500");
    lv_obj_set_style_text_color(ui_LabelShiftMax1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelShiftMax1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShiftMax1, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelShiftMax2 = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelShiftMax2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelShiftMax2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelShiftMax2, 496 );
    lv_obj_set_y( ui_LabelShiftMax2, 360 );
    lv_label_set_text(ui_LabelShiftMax2,"7500");
    lv_obj_set_style_text_color(ui_LabelShiftMax2, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelShiftMax2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShiftMax2, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelPoilMini = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelPoilMini, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelPoilMini, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelPoilMini, 114 );
    lv_obj_set_y( ui_LabelPoilMini, 510 );
    lv_label_set_text(ui_LabelPoilMini,"2.5");
    lv_obj_set_style_text_color(ui_LabelPoilMini, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelPoilMini, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPoilMini, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelRPMOilMini = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelRPMOilMini, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelRPMOilMini, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelRPMOilMini, 220 );
    lv_obj_set_y( ui_LabelRPMOilMini, 510 );
    lv_label_set_text(ui_LabelRPMOilMini,"2000");
    lv_obj_set_style_text_color(ui_LabelRPMOilMini, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelRPMOilMini, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRPMOilMini, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelTeauMax = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_LabelTeauMax, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelTeauMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelTeauMax, 500 );
    lv_obj_set_y( ui_LabelTeauMax, 510 );
    lv_label_set_text(ui_LabelTeauMax,"102");
    lv_obj_set_style_text_color(ui_LabelTeauMax, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_LabelTeauMax, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTeauMax, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_ButtonHome2 = lv_btn_create(ui_ScreenLeds);
    lv_obj_set_width( ui_ButtonHome2, 255);
    lv_obj_set_height( ui_ButtonHome2, 76);
    lv_obj_add_flag( ui_ButtonHome2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
    lv_obj_clear_flag( ui_ButtonHome2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_radius(ui_ButtonHome2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonHome2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_ButtonHome2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Horloge2 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_Horloge2, 140);
    lv_obj_set_height( ui_Horloge2, 45);
    lv_obj_set_x( ui_Horloge2, -363 );
    lv_obj_set_y( ui_Horloge2, -262 );
    lv_obj_set_align( ui_Horloge2, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_Horloge2,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Horloge2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_Horloge2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_radius(ui_Horloge2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Horloge2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_Horloge2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Horloge2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_border_opa(ui_Horloge2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelHeure2 = lv_label_create(ui_Horloge2);
    lv_obj_set_width( ui_LabelHeure2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelHeure2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelHeure2, -51 );
    lv_obj_set_y( ui_LabelHeure2, -2 );
    lv_obj_set_align( ui_LabelHeure2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_LabelHeure2,"15");
    lv_obj_set_style_text_font(ui_LabelHeure2, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelSepHeureMin2 = lv_label_create(ui_Horloge2);
    lv_obj_set_width( ui_LabelSepHeureMin2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelSepHeureMin2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelSepHeureMin2, -13 );
    lv_obj_set_y( ui_LabelSepHeureMin2, -7 );
    lv_obj_set_align( ui_LabelSepHeureMin2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_LabelSepHeureMin2,":");
    lv_obj_set_style_text_font(ui_LabelSepHeureMin2, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LabelMin2 = lv_label_create(ui_Horloge2);
    lv_obj_set_width( ui_LabelMin2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_LabelMin2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_LabelMin2, 29 );
    lv_obj_set_y( ui_LabelMin2, -1 );
    lv_obj_set_align( ui_LabelMin2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_LabelMin2,"35");
    lv_obj_set_style_text_font(ui_LabelMin2, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);



    ui_console_label = lv_label_create(ui_ScreenLeds);
    lv_obj_set_width( ui_console_label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_console_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_console_label, 366 );
    lv_obj_set_y( ui_console_label, -4 );
    lv_obj_set_align( ui_console_label, LV_ALIGN_CENTER );
    lv_obj_set_style_text_color(ui_console_label, lv_color_hex(0x00FFF0), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_console_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_console_label, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_console_label, 3, 0);
    update_console_display();

    ui_key1 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_key1, 69);
    lv_obj_set_height( ui_key1, 45);
    lv_obj_set_x( ui_key1, 202 );
    lv_obj_set_y( ui_key1, 51 );
    lv_obj_set_align( ui_key1, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_key1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_key1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_key1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_key1);

    ui_key2 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_key2, 69);
    lv_obj_set_height( ui_key2, 45);
    lv_obj_set_x( ui_key2, 293 );
    lv_obj_set_y( ui_key2, 51 );
    lv_obj_set_align( ui_key2, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_key2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_key2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_key2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_key2);

    ui_key3 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_key3, 69);
    lv_obj_set_height( ui_key3, 45);
    lv_obj_set_x( ui_key3, 384 );
    lv_obj_set_y( ui_key3, 51 );
    lv_obj_set_align( ui_key3, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_key3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_key3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_key3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_key3);

    ui_key4 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_key4, 69);
    lv_obj_set_height( ui_key4, 45);
    lv_obj_set_x( ui_key4, 202 );
    lv_obj_set_y( ui_key4, 115 );
    lv_obj_set_align( ui_key4, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_key4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_key4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_key4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_key4);

    ui_key5 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_key5, 69);
    lv_obj_set_height( ui_key5, 45);
    lv_obj_set_x( ui_key5, 293 );
    lv_obj_set_y( ui_key5, 115 );
    lv_obj_set_align( ui_key5, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_key5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_key5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_key5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_key5);

    ui_key6 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_key6, 69);
    lv_obj_set_height( ui_key6, 45);
    lv_obj_set_x( ui_key6, 384 );
    lv_obj_set_y( ui_key6, 115 );
    lv_obj_set_align( ui_key6, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_key6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_key6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_key6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_key6);

    ui_key7 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_key7, 69);
    lv_obj_set_height( ui_key7, 45);
    lv_obj_set_x( ui_key7, 202 );
    lv_obj_set_y( ui_key7, 179 );
    lv_obj_set_align( ui_key7, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_key7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_key7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_key7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_key7);

    ui_key8 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_key8, 69);
    lv_obj_set_height( ui_key8, 45);
    lv_obj_set_x( ui_key8, 293 );
    lv_obj_set_y( ui_key8, 179 );
    lv_obj_set_align( ui_key8, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_key8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_key8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_key8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_key8);

    ui_key9 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_key9, 69);
    lv_obj_set_height( ui_key9, 45);
    lv_obj_set_x( ui_key9, 384 );
    lv_obj_set_y( ui_key9, 179 );
    lv_obj_set_align( ui_key9, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_key9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_key9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_key9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_key9);

    ui_keybackspace = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_keybackspace, 69);
    lv_obj_set_height( ui_keybackspace, 45);
    lv_obj_set_x( ui_keybackspace, 202 );
    lv_obj_set_y( ui_keybackspace, 243 );
    lv_obj_set_align( ui_keybackspace, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_keybackspace, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_keybackspace, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_keybackspace, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_keybackspace);

    ui_key0 = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_key0, 69);
    lv_obj_set_height( ui_key0, 45);
    lv_obj_set_x( ui_key0, 293 );
    lv_obj_set_y( ui_key0, 243 );
    lv_obj_set_align( ui_key0, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_key0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_key0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_key0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_key0);

    ui_keydot = lv_obj_create(ui_ScreenLeds);
    lv_obj_set_width( ui_keydot, 69);
    lv_obj_set_height( ui_keydot, 45);
    lv_obj_set_x( ui_keydot, 384 );
    lv_obj_set_y( ui_keydot, 243 );
    lv_obj_set_align( ui_keydot, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_keydot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_opa(ui_keydot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_keydot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    add_key_highlighting(ui_keydot);




    lv_obj_add_event_cb(ui_PanelShift1, ui_event_PanelShift1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShift2, ui_event_PanelShift2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShift3, ui_event_PanelShift3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShift4, ui_event_PanelShift4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShift5, ui_event_PanelShift5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShift6, ui_event_PanelShift6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShift7, ui_event_PanelShift7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShift8, ui_event_PanelShift8, LV_EVENT_ALL, NULL);
    
    lv_obj_add_event_cb(ui_PanelShiftMaxi1, ui_event_PanelShiftMaxi1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShiftMaxi2, ui_event_PanelShiftMaxi2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShiftMaxi3, ui_event_PanelShiftMaxi3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShiftMaxi4, ui_event_PanelShiftMaxi4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelShiftMaxi5, ui_event_PanelShiftMaxi5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelPOil, ui_event_PanelPOil, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelTempWater, ui_event_PanelTempWater, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_ButtonHome2, ui_event_ButtonHome2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenLeds, ui_event_ScreenLeds, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_greenledpanel, ui_event_greenledpanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_orangeledpanel, ui_event_orangeledpanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_redledpanel, ui_event_redledpanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cyanledpanel, ui_event_cyanledpanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_blueledpanel, ui_event_blueledpanel, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_key1, ui_event_key1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_key2, ui_event_key2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_key3, ui_event_key3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_key4, ui_event_key4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_key5, ui_event_key5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_key6, ui_event_key6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_key7, ui_event_key7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_key8, ui_event_key8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_key9, ui_event_key9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_keybackspace, ui_event_keybackspace, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_key0, ui_event_key0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_keydot, ui_event_keydot, LV_EVENT_ALL, NULL);

    uic_PanelShift1 = ui_PanelShift1;
    uic_PanelShift2 = ui_PanelShift2;
    uic_PanelShift3 = ui_PanelShift3;
    uic_PanelShift4 = ui_PanelShift4;
    uic_PanelShift5 = ui_PanelShift5;
    uic_PanelShift6 = ui_PanelShift6;
    uic_PanelShift7 = ui_PanelShift7;
    uic_PanelShift8 = ui_PanelShift8; 

    uic_PanelShiftMaxi1 = ui_PanelShiftMaxi1;
    uic_PanelShiftMaxi2 = ui_PanelShiftMaxi2;
    uic_PanelShiftMaxi3 = ui_PanelShiftMaxi3;
    uic_PanelShiftMaxi4 = ui_PanelShiftMaxi4;
    uic_PanelShiftMaxi5 = ui_PanelShiftMaxi5;
    uic_PanelPOil = ui_PanelPOil;
    uic_PanelTempWater = ui_PanelTempWater; 

    uic_greenledpanel = ui_greenledpanel;
    uic_orangeledpanel = ui_orangeledpanel;
    uic_redledpanel = ui_redledpanel;
    uic_cyanledpanel = ui_cyanledpanel;
    uic_blueledpanel = ui_blueledpanel;

    uic_LabelShift1 = ui_LabelShift1;
    uic_LabelShift2 = ui_LabelShift2;
    uic_LabelShift3 = ui_LabelShift3;
    uic_LabelShift4 = ui_LabelShift4;
    uic_LabelShift5 = ui_LabelShift5;
    uic_LabelShift6 = ui_LabelShift6;
    uic_LabelShift7 = ui_LabelShift7;
    uic_LabelShift8 = ui_LabelShift8;
    uic_LabelShiftMax1 = ui_LabelShiftMax1;
    uic_LabelShiftMax2 = ui_LabelShiftMax2;
    uic_LabelPoilMini = ui_LabelPoilMini;
    uic_LabelRPMOilMini = ui_LabelRPMOilMini;
    uic_LabelTeauMax = ui_LabelTeauMax;
    uic_ButtonHome2 = ui_ButtonHome2;
    uic_Horloge2 = ui_Horloge2;
    uic_LabelHeure2 = ui_LabelHeure2;
    uic_LabelSepHeureMin2 = ui_LabelSepHeureMin2;
    uic_LabelMin2 = ui_LabelMin2;

    uic_console_label = ui_console_label;
    uic_key1 = ui_key1;
    uic_key2 = ui_key2;
    uic_key3 = ui_key3;
    uic_key4 = ui_key4;
    uic_key5 = ui_key5;
    uic_key6 = ui_key6;
    uic_key7 = ui_key7;
    uic_key8 = ui_key8;
    uic_keybackspace = ui_keybackspace;
    uic_key0 = ui_key0;
    uic_keydot = ui_keydot;

}

void ui_ScreenLeds_screen_destroy(void)
{
    if (ui_ScreenLeds) lv_obj_del(ui_ScreenLeds);

    // NULL screen variables
    ui_ScreenLeds= NULL;
    
    uic_PanelShift1 = NULL;
    ui_PanelShift1 = NULL;

    uic_PanelShift2 = NULL;
    ui_PanelShift2 = NULL;

    uic_PanelShift3 = NULL;
    ui_PanelShift3 = NULL;

    uic_PanelShift4 = NULL;
    ui_PanelShift4 = NULL;

    uic_PanelShift5 = NULL;
    ui_PanelShift5 = NULL;

    uic_PanelShift6 = NULL;
    ui_PanelShift6 = NULL;

    uic_PanelShift7 = NULL;
    ui_PanelShift7 = NULL;

    uic_PanelShift8 = NULL;
    ui_PanelShift8 = NULL;

    uic_PanelShiftMaxi1 = NULL;
    ui_PanelShiftMaxi1 = NULL;

    uic_PanelShiftMaxi2 = NULL;
    ui_PanelShiftMaxi2 = NULL;

    uic_PanelShiftMaxi3 = NULL;
    ui_PanelShiftMaxi3 = NULL;

    uic_PanelShiftMaxi4 = NULL;
    ui_PanelShiftMaxi4 = NULL;

    uic_PanelShiftMaxi5 = NULL;
    ui_PanelShiftMaxi5 = NULL;

    uic_PanelPOil = NULL;
    ui_PanelPOil = NULL;

    uic_PanelTempWater = NULL;
    ui_PanelTempWater = NULL;

    ui_greenledpanel = NULL;
    uic_greenledpanel = NULL;

    ui_orangeledpanel = NULL;
    uic_orangeledpanel = NULL;

    ui_redledpanel = NULL;
    uic_redledpanel = NULL;

    ui_cyanledpanel = NULL;
    uic_cyanledpanel = NULL;

    ui_blueledpanel = NULL;
    uic_blueledpanel = NULL;

    uic_LabelShift1= NULL;
    ui_LabelShift1= NULL;
    uic_LabelShift2= NULL;
    ui_LabelShift2= NULL;
    uic_LabelShift3= NULL;
    ui_LabelShift3= NULL;
    uic_LabelShift4= NULL;
    ui_LabelShift4= NULL;
    uic_LabelShift5= NULL;
    ui_LabelShift5= NULL;
    uic_LabelShift6= NULL;
    ui_LabelShift6= NULL;
    uic_LabelShift7= NULL;
    ui_LabelShift7= NULL;
    uic_LabelShift8= NULL;
    ui_LabelShift8= NULL;
    uic_LabelShiftMax1= NULL;
    ui_LabelShiftMax1= NULL;
    uic_LabelShiftMax2= NULL;
    ui_LabelShiftMax2= NULL;
    uic_LabelPoilMini= NULL;
    ui_LabelPoilMini= NULL;
    uic_LabelRPMOilMini= NULL;
    ui_LabelRPMOilMini= NULL;
    uic_LabelTeauMax= NULL;
    ui_LabelTeauMax= NULL;
    uic_ButtonHome2= NULL;
    ui_ButtonHome2= NULL;
    uic_Horloge2= NULL;
    ui_Horloge2= NULL;
    uic_LabelHeure2= NULL;
    ui_LabelHeure2= NULL;
    uic_LabelSepHeureMin2= NULL;
    ui_LabelSepHeureMin2= NULL;
    uic_LabelMin2= NULL;
    ui_LabelMin2= NULL;


    uic_console_label= NULL;
    ui_console_label= NULL;
    uic_key1= NULL;
    ui_key1= NULL;
    uic_key2= NULL;
    ui_key2= NULL;
    uic_key3= NULL;
    ui_key3= NULL;
    uic_key4= NULL;
    ui_key4= NULL;
    uic_key5= NULL;
    ui_key5= NULL;
    uic_key6= NULL;
    ui_key6= NULL;
    uic_key7= NULL;
    ui_key7= NULL;
    uic_key8= NULL;
    ui_key8= NULL;
    ui_key9= NULL;
    uic_key9=NULL;
    uic_keybackspace= NULL;
    ui_keybackspace= NULL;
    uic_key0= NULL;
    ui_key0= NULL;
    uic_keydot= NULL;
    ui_keydot= NULL;

}
