// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#ifndef UI_SCREENLEDS_H
#define UI_SCREENLEDS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenLeds
extern void ui_ScreenLeds_screen_init(void);
extern void ui_ScreenLeds_screen_destroy(void);
extern void ui_event_ScreenLeds( lv_event_t * e);
extern lv_obj_t *ui_ScreenLeds;
extern lv_obj_t *ui_LabelShift1;
extern lv_obj_t *ui_LabelShift2;
extern lv_obj_t *ui_LabelShift3;
extern lv_obj_t *ui_LabelShift4;
extern lv_obj_t *ui_LabelShift5;
extern lv_obj_t *ui_LabelShift6;
extern lv_obj_t *ui_LabelShift7;
extern lv_obj_t *ui_LabelShift8;
extern lv_obj_t *ui_LabelShiftMax1;
extern lv_obj_t *ui_LabelShiftMax2;
extern lv_obj_t *ui_LabelPoilMini;
extern lv_obj_t *ui_LabelRPMOilMini;
extern lv_obj_t *ui_LabelTeauMax;
extern void ui_event_ButtonHome2( lv_event_t * e);
extern lv_obj_t *ui_ButtonHome2;
extern lv_obj_t *ui_Horloge2;
extern lv_obj_t *ui_LabelHeure2;
extern lv_obj_t *ui_LabelSepHeureMin2;
extern lv_obj_t *ui_LabelMin2;


extern lv_obj_t *ui_PanelShift1;
extern lv_obj_t *ui_PanelShift2;
extern lv_obj_t *ui_PanelShift3;
extern lv_obj_t *ui_PanelShift4;
extern lv_obj_t *ui_PanelShift5;
extern lv_obj_t *ui_PanelShift6;
extern lv_obj_t *ui_PanelShift7;
extern lv_obj_t *ui_PanelShift8;
extern lv_obj_t *ui_PanelShiftMaxi1;
extern lv_obj_t *ui_PanelShiftMaxi2;
extern lv_obj_t *ui_PanelShiftMaxi3;
extern lv_obj_t *ui_PanelShiftMaxi4;
extern lv_obj_t *ui_PanelShiftMaxi5;
extern lv_obj_t *ui_PanelPOil;
extern lv_obj_t *ui_PanelTempWater;

// CUSTOM VARIABLES
extern lv_obj_t *uic_LabelShift1;
extern lv_obj_t *uic_LabelShift2;
extern lv_obj_t *uic_LabelShift3;
extern lv_obj_t *uic_LabelShift4;
extern lv_obj_t *uic_LabelShift5;
extern lv_obj_t *uic_LabelShift6;
extern lv_obj_t *uic_LabelShift7;
extern lv_obj_t *uic_LabelShift8;
extern lv_obj_t *uic_LabelShiftMax1;
extern lv_obj_t *uic_LabelShiftMax2;
extern lv_obj_t *uic_LabelPoilMini;
extern lv_obj_t *uic_LabelRPMOilMini;
extern lv_obj_t *uic_LabelTeauMax;
extern lv_obj_t *uic_ButtonHome2;
extern lv_obj_t *uic_Horloge2;
extern lv_obj_t *uic_LabelHeure2;
extern lv_obj_t *uic_LabelSepHeureMin2;
extern lv_obj_t *uic_LabelMin2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

