// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#ifndef UI_SCREENDISPLAYRX_H
#define UI_SCREENDISPLAYRX_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenDisplayRX
extern void ui_ScreenDisplayRX_screen_init(void);
extern void ui_ScreenDisplayRX_screen_destroy(void);
extern void ui_event_ScreenDisplayRX( lv_event_t * e);
extern lv_obj_t *ui_ScreenDisplayRX;
extern lv_obj_t *ui_PanelGauche;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label1Value;
extern lv_obj_t *ui_Label2Value;
extern lv_obj_t *ui_Label3Value;
extern lv_obj_t *ui_PanelCentre;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label4Value;
extern lv_obj_t *ui_Label5Value;
extern lv_obj_t *ui_PanelDroiteHaut;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label6Value;
extern lv_obj_t *ui_PanelDroiteBas;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label7Value;
extern lv_obj_t *ui_LabelRPM;
extern lv_obj_t *ui_LabelRPMValue;
extern lv_obj_t *ui_BarFirstPart;
extern lv_obj_t *ui_BarSecondPart;
extern void ui_event_ButtonHome( lv_event_t * e);
extern lv_obj_t *ui_ButtonHome;
extern lv_obj_t *ui_Horloge;
extern lv_obj_t *ui_LabelHeure;
extern lv_obj_t *ui_LabelSepHeureMin;
extern lv_obj_t *ui_LabelMin;
extern lv_obj_t *ui_ALERTETEAU;
extern lv_obj_t *ui_LabelAlerteEau;
extern lv_obj_t *ui_ALERTEPOIL;
extern lv_obj_t *ui_LabelAlerteOil;

// CUSTOM VARIABLES
extern lv_obj_t *uic_PanelGauche;
extern lv_obj_t *uic_Panel1;
extern lv_obj_t *uic_Label1;
extern lv_obj_t *uic_Label2;
extern lv_obj_t *uic_Label3;
extern lv_obj_t *uic_Panel4;
extern lv_obj_t *uic_Label1Value;
extern lv_obj_t *uic_Label2Value;
extern lv_obj_t *uic_Label3Value;
extern lv_obj_t *uic_PanelCentre;
extern lv_obj_t *uic_Label4;
extern lv_obj_t *uic_Label5;
extern lv_obj_t *uic_Label4Value;
extern lv_obj_t *uic_Label5Value;
extern lv_obj_t *uic_PanelDroiteHaut;
extern lv_obj_t *uic_Label6;
extern lv_obj_t *uic_Label6Value;
extern lv_obj_t *uic_PanelDroiteBas;
extern lv_obj_t *uic_Label7;
extern lv_obj_t *uic_Label7Value;
extern lv_obj_t *uic_LabelRPM;
extern lv_obj_t *uic_LabelRPMValue;
extern lv_obj_t *uic_BarFirstPart;
extern lv_obj_t *uic_BarSecondPart;
extern lv_obj_t *uic_ButtonHome;
extern lv_obj_t *uic_Horloge;
extern lv_obj_t *uic_LabelHeure;
extern lv_obj_t *uic_LabelSepHeureMin;
extern lv_obj_t *uic_LabelMin;
extern lv_obj_t *uic_ALERTETEAU;
extern lv_obj_t *uic_LabelAlerteEau;
extern lv_obj_t *uic_ALERTEPOIL;
extern lv_obj_t *uic_LabelAlerteOil;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

