// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#ifndef UI_SCREENDISPLAYBV_H
#define UI_SCREENDISPLAYBV_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenDisplayBV
extern void ui_ScreenDisplayBV_screen_init(void);
extern void ui_ScreenDisplayBV_screen_destroy(void);
extern void ui_event_ScreenDisplayBV( lv_event_t * e);
extern lv_obj_t *ui_ScreenDisplayBV;
extern lv_obj_t *ui_PanelGauche1;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label1Value1;
extern lv_obj_t *ui_Label2Value1;
extern lv_obj_t *ui_Label3Value1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Dropdown1;
extern lv_obj_t *ui_Dropdown2;
extern lv_obj_t *ui_Dropdown3;
extern lv_obj_t *ui_PanelDroiteHaut1;
extern lv_obj_t *ui_Label6Value1;
extern lv_obj_t *ui_Dropdown4;
extern lv_obj_t *ui_PanelDroiteBas1;
extern lv_obj_t *ui_Label7Value1;
extern lv_obj_t *ui_Dropdown5;
extern lv_obj_t *ui_LabelRPM1;
extern lv_obj_t *ui_LabelRPMValue1;
extern lv_obj_t *ui_BarFirstPart1;
extern lv_obj_t *ui_BarSecondPart1;
extern void ui_event_ButtonHome3( lv_event_t * e);
extern lv_obj_t *ui_ButtonHome3;
extern lv_obj_t *ui_Horloge1;
extern lv_obj_t *ui_LabelHeure1;
extern lv_obj_t *ui_LabelSepHeureMin1;
extern lv_obj_t *ui_LabelMin1;
extern lv_obj_t *ui_ImageCadreRapportBV;
extern lv_obj_t *ui_LabelRapportBV;
extern lv_obj_t *ui_ALERTETEAU1;
extern lv_obj_t *ui_LabelAlerteEau1;
extern lv_obj_t *ui_ALERTEPOIL1;
extern lv_obj_t *ui_LabelAlerteOil1;

// CUSTOM VARIABLES
extern lv_obj_t *uic_PanelGauche1;
extern lv_obj_t *uic_Panel3;
extern lv_obj_t *uic_Label1Value1;
extern lv_obj_t *uic_Label2Value1;
extern lv_obj_t *uic_Label3Value1;
extern lv_obj_t *uic_Panel2;
extern lv_obj_t *uic_Dropdown1;
extern lv_obj_t *uic_Dropdown2;
extern lv_obj_t *uic_Dropdown3;
extern lv_obj_t *uic_PanelDroiteHaut1;
extern lv_obj_t *uic_Label6Value1;
extern lv_obj_t *uic_Dropdown4;
extern lv_obj_t *uic_PanelDroiteBas1;
extern lv_obj_t *uic_Label7Value1;
extern lv_obj_t *uic_Dropdown5;
extern lv_obj_t *uic_LabelRPM1;
extern lv_obj_t *uic_LabelRPMValue1;
extern lv_obj_t *uic_BarFirstPart1;
extern lv_obj_t *uic_BarSecondPart1;
extern lv_obj_t *uic_ButtonHome3;
extern lv_obj_t *uic_Horloge1;
extern lv_obj_t *uic_LabelHeure1;
extern lv_obj_t *uic_LabelSepHeureMin1;
extern lv_obj_t *uic_LabelMin1;
extern lv_obj_t *uic_ImageCadreRapportBV;
extern lv_obj_t *uic_LabelRapportBV;
extern lv_obj_t *uic_ALERTETEAU1;
extern lv_obj_t *uic_LabelAlerteEau1;
extern lv_obj_t *uic_ALERTEPOIL1;
extern lv_obj_t *uic_LabelAlerteOil1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

