// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#include "../ui_manager.h"

lv_obj_t *uic_LabelMin4;
lv_obj_t *uic_LabelSepHeureMin4;
lv_obj_t *uic_LabelHeure4;
lv_obj_t *uic_Horloge4;
lv_obj_t *ui_ScreenRealTime = NULL;lv_obj_t *ui_Horloge4 = NULL;lv_obj_t *ui_LabelHeure4 = NULL;lv_obj_t *ui_LabelSepHeureMin4 = NULL;lv_obj_t *ui_LabelMin4 = NULL;lv_obj_t *ui_ButtonHome4 = NULL;lv_obj_t *ui_Label3Value2 = NULL;lv_obj_t *ui_Label3Value3 = NULL;lv_obj_t *ui_Label3Value4 = NULL;lv_obj_t *ui_Label3Value5 = NULL;lv_obj_t *ui_Label3Value6 = NULL;lv_obj_t *ui_Label3Value7 = NULL;lv_obj_t *ui_Label3Value8 = NULL;lv_obj_t *ui_Label3Value9 = NULL;lv_obj_t *ui_Label3Value10 = NULL;lv_obj_t *ui_Label3Value11 = NULL;lv_obj_t *ui_Label3Value12 = NULL;lv_obj_t *ui_Label3Value13 = NULL;lv_obj_t *ui_Label3Value14 = NULL;
// event funtions
void ui_event_ButtonHome4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMenu_screen_init);
}
}

// build funtions

void ui_ScreenRealTime_screen_init(void)
{
ui_ScreenRealTime = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenRealTime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_ScreenRealTime, &ui_img_1642545580, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Horloge4 = lv_obj_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Horloge4, 130);
lv_obj_set_height( ui_Horloge4, 45);
lv_obj_set_x( ui_Horloge4, -363 );
lv_obj_set_y( ui_Horloge4, -262 );
lv_obj_set_align( ui_Horloge4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Horloge4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Horloge4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Horloge4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Horloge4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Horloge4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Horloge4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Horloge4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Horloge4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHeure4 = lv_label_create(ui_Horloge4);
lv_obj_set_width( ui_LabelHeure4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHeure4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHeure4, -51 );
lv_obj_set_y( ui_LabelHeure4, -2 );
lv_obj_set_align( ui_LabelHeure4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHeure4,"15");
lv_obj_set_style_text_font(ui_LabelHeure4, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSepHeureMin4 = lv_label_create(ui_Horloge4);
lv_obj_set_width( ui_LabelSepHeureMin4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSepHeureMin4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSepHeureMin4, -13 );
lv_obj_set_y( ui_LabelSepHeureMin4, -7 );
lv_obj_set_align( ui_LabelSepHeureMin4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSepHeureMin4,":");
lv_obj_set_style_text_font(ui_LabelSepHeureMin4, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMin4 = lv_label_create(ui_Horloge4);
lv_obj_set_width( ui_LabelMin4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMin4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMin4, 29 );
lv_obj_set_y( ui_LabelMin4, -1 );
lv_obj_set_align( ui_LabelMin4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMin4,"35");
lv_obj_set_style_text_font(ui_LabelMin4, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonHome4 = lv_btn_create(ui_ScreenRealTime);
lv_obj_set_width( ui_ButtonHome4, 62);
lv_obj_set_height( ui_ButtonHome4, 52);
lv_obj_set_x( ui_ButtonHome4, 10 );
lv_obj_set_y( ui_ButtonHome4, 12 );
lv_obj_add_flag( ui_ButtonHome4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonHome4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonHome4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonHome4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonHome4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value2 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value2, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value2, -377 );
lv_obj_set_y( ui_Label3Value2, 175 );
lv_obj_set_align( ui_Label3Value2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value2,"6750");
lv_obj_set_style_text_color(ui_Label3Value2, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value2, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value3 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value3, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value3, -125 );
lv_obj_set_y( ui_Label3Value3, 175 );
lv_obj_set_align( ui_Label3Value3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value3,"100");
lv_obj_set_style_text_color(ui_Label3Value3, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value3, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value4 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value4, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Label3Value4, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value4, 125 );
lv_obj_set_y( ui_Label3Value4, 175 );
lv_obj_set_align( ui_Label3Value4, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value4,"0.84");
lv_obj_set_style_text_color(ui_Label3Value4, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value4, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value5 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value5, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value5, 377 );
lv_obj_set_y( ui_Label3Value5, 175 );
lv_obj_set_align( ui_Label3Value5, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value5,"25");
lv_obj_set_style_text_color(ui_Label3Value5, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value5, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value6 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value6, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value6, -377 );
lv_obj_set_y( ui_Label3Value6, 342 );
lv_obj_set_align( ui_Label3Value6, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value6,"87");
lv_obj_set_style_text_color(ui_Label3Value6, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value6, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value7 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value7, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value7, -125 );
lv_obj_set_y( ui_Label3Value7, 342 );
lv_obj_set_align( ui_Label3Value7, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value7,"26");
lv_obj_set_style_text_color(ui_Label3Value7, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value7, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value8 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value8, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value8, 125 );
lv_obj_set_y( ui_Label3Value8, 342 );
lv_obj_set_align( ui_Label3Value8, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value8,"115");
lv_obj_set_style_text_color(ui_Label3Value8, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value8, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value9 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value9, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value9, 377 );
lv_obj_set_y( ui_Label3Value9, 342 );
lv_obj_set_align( ui_Label3Value9, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value9,"35");
lv_obj_set_style_text_color(ui_Label3Value9, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value9, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value10 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value10, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value10, -377 );
lv_obj_set_y( ui_Label3Value10, 510 );
lv_obj_set_align( ui_Label3Value10, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value10,"4.2");
lv_obj_set_style_text_color(ui_Label3Value10, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value10, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value11 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value11, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value11, -125 );
lv_obj_set_y( ui_Label3Value11, 510 );
lv_obj_set_align( ui_Label3Value11, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value11,"3.9");
lv_obj_set_style_text_color(ui_Label3Value11, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value11, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value12 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value12, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value12, 125 );
lv_obj_set_y( ui_Label3Value12, 510 );
lv_obj_set_align( ui_Label3Value12, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value12,"1013");
lv_obj_set_style_text_color(ui_Label3Value12, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value12, &ui_font_VerdanaBoldItalic60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value13 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value13, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value13, 311 );
lv_obj_set_y( ui_Label3Value13, 528 );
lv_obj_set_align( ui_Label3Value13, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value13,"0");
lv_obj_set_style_text_color(ui_Label3Value13, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value13, &ui_font_VerdanaBoldItalic55, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value14 = lv_label_create(ui_ScreenRealTime);
lv_obj_set_width( ui_Label3Value14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3Value14, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Label3Value14, 433 );
lv_obj_set_y( ui_Label3Value14, 528 );
lv_obj_set_align( ui_Label3Value14, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3Value14,"1");
lv_obj_set_style_text_color(ui_Label3Value14, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value14, &ui_font_VerdanaBoldItalic55, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonHome4, ui_event_ButtonHome4, LV_EVENT_ALL, NULL);
uic_Horloge4 = ui_Horloge4;
uic_LabelHeure4 = ui_LabelHeure4;
uic_LabelSepHeureMin4 = ui_LabelSepHeureMin4;
uic_LabelMin4 = ui_LabelMin4;

}

void ui_ScreenRealTime_screen_destroy(void)
{
   if (ui_ScreenRealTime) lv_obj_del(ui_ScreenRealTime);

// NULL screen variables
ui_ScreenRealTime= NULL;
uic_Horloge4= NULL;
ui_Horloge4= NULL;
uic_LabelHeure4= NULL;
ui_LabelHeure4= NULL;
uic_LabelSepHeureMin4= NULL;
ui_LabelSepHeureMin4= NULL;
uic_LabelMin4= NULL;
ui_LabelMin4= NULL;
ui_ButtonHome4= NULL;
ui_Label3Value2= NULL;
ui_Label3Value3= NULL;
ui_Label3Value4= NULL;
ui_Label3Value5= NULL;
ui_Label3Value6= NULL;
ui_Label3Value7= NULL;
ui_Label3Value8= NULL;
ui_Label3Value9= NULL;
ui_Label3Value10= NULL;
ui_Label3Value11= NULL;
ui_Label3Value12= NULL;
ui_Label3Value13= NULL;
ui_Label3Value14= NULL;

}
