// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#include "../ui_manager.h"

lv_obj_t *uic_LabelAlerteOil;
lv_obj_t *uic_ALERTEPOIL;
lv_obj_t *uic_LabelAlerteEau;
lv_obj_t *uic_ALERTETEAU;
lv_obj_t *uic_LabelMin;
lv_obj_t *uic_LabelSepHeureMin;
lv_obj_t *uic_LabelHeure;
lv_obj_t *uic_Horloge;
lv_obj_t *uic_ButtonHome;
lv_obj_t *uic_BarSecondPart;
lv_obj_t *uic_BarFirstPart;
lv_obj_t *uic_LabelRPMValue;
lv_obj_t *uic_LabelRPM;
lv_obj_t *uic_Label7Value;
lv_obj_t *uic_Label7;
lv_obj_t *uic_PanelDroiteBas;
lv_obj_t *uic_Label6Value;
lv_obj_t *uic_Label6;
lv_obj_t *uic_PanelDroiteHaut;
lv_obj_t *uic_Label5Value;
lv_obj_t *uic_Label4Value;
lv_obj_t *uic_Label5;
lv_obj_t *uic_Label4;
lv_obj_t *uic_PanelCentre;
lv_obj_t *uic_Label3Value;
lv_obj_t *uic_Label2Value;
lv_obj_t *uic_Label1Value;
lv_obj_t *uic_Panel4;
lv_obj_t *uic_Label3;
lv_obj_t *uic_Label2;
lv_obj_t *uic_Label1;
lv_obj_t *uic_Panel1;
lv_obj_t *uic_PanelGauche;
lv_obj_t *ui_ScreenDisplayRX = NULL;
lv_obj_t *ui_PanelGauche = NULL;
lv_obj_t *ui_Panel1 = NULL;
lv_obj_t *ui_Label1 = NULL;
lv_obj_t *ui_Label2 = NULL;
lv_obj_t *ui_Label3 = NULL;
lv_obj_t *ui_Panel4 = NULL;
lv_obj_t *ui_Label1Value = NULL;
lv_obj_t *ui_Label2Value = NULL;
lv_obj_t *ui_Label3Value = NULL;
lv_obj_t *ui_PanelCentre = NULL;
lv_obj_t *ui_Label4 = NULL;
lv_obj_t *ui_Label5 = NULL;
lv_obj_t *ui_Label4Value = NULL;
lv_obj_t *ui_Label5Value = NULL;
lv_obj_t *ui_PanelDroiteHaut = NULL;
lv_obj_t *ui_Label6 = NULL;
lv_obj_t *ui_Label6Value = NULL;
lv_obj_t *ui_PanelDroiteBas = NULL;
lv_obj_t *ui_Label7 = NULL;
lv_obj_t *ui_Label7Value = NULL;
lv_obj_t *ui_LabelRPM = NULL;
lv_obj_t *ui_LabelRPMValue = NULL;
lv_obj_t *ui_BarFirstPart = NULL;
lv_obj_t *ui_BarSecondPart = NULL;
lv_obj_t *ui_ButtonHome = NULL;
lv_obj_t *ui_Horloge = NULL;
lv_obj_t *ui_LabelHeure = NULL;
lv_obj_t *ui_LabelSepHeureMin = NULL;
lv_obj_t *ui_LabelMin = NULL;
lv_obj_t *ui_ALERTETEAU = NULL;
lv_obj_t *ui_LabelAlerteEau = NULL;
lv_obj_t *ui_ALERTEPOIL = NULL;
lv_obj_t *ui_LabelAlerteOil = NULL;

// event funtions
void ui_event_ScreenDisplayRX( lv_event_t * e) {
      lv_event_code_t event_code = lv_event_get_code(e);

      if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) 
      {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change( &ui_ScreenDisplayBV, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenDisplayBV_screen_init);
      }     

      if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) 
      {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change( &ui_ScreenDisplayBV, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenDisplayBV_screen_init);
      }
}

void ui_event_ButtonHome( lv_event_t * e) {
      lv_event_code_t event_code = lv_event_get_code(e);

      if ( event_code == LV_EVENT_CLICKED)
      {
            _ui_screen_change( &ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMenu_screen_init);
      }
}

// build funtions

void ui_ScreenDisplayRX_screen_init(void)
{
      ui_ScreenDisplayRX = lv_obj_create(NULL);
      lv_obj_clear_flag( ui_ScreenDisplayRX, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_bg_img_src( ui_ScreenDisplayRX, &ui_img_gddash_70_fond_png, LV_PART_MAIN | LV_STATE_DEFAULT );

      ui_PanelGauche = lv_obj_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_PanelGauche, 294);
      lv_obj_set_height( ui_PanelGauche, 226);
      lv_obj_set_x( ui_PanelGauche, 18 );
      lv_obj_set_y( ui_PanelGauche, -16 );
      lv_obj_set_align( ui_PanelGauche, LV_ALIGN_BOTTOM_LEFT );
      lv_obj_clear_flag( ui_PanelGauche, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_radius(ui_PanelGauche, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_PanelGauche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_PanelGauche, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_PanelGauche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_border_opa(ui_PanelGauche, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_width(ui_PanelGauche, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Panel1 = lv_obj_create(ui_PanelGauche);
      lv_obj_set_width( ui_Panel1, 150);
      lv_obj_set_height( ui_Panel1, 206);
      lv_obj_set_x( ui_Panel1, -55 );
      lv_obj_set_y( ui_Panel1, 2 );
      lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
      lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_COLUMN);
      lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
      lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label1 = lv_label_create(ui_Panel1);
      lv_obj_set_width( ui_Label1, 150);
      lv_obj_set_height( ui_Label1, 40);
      lv_obj_set_x( ui_Label1, -4 );
      lv_obj_set_y( ui_Label1, lv_pct(-40) );
      lv_label_set_text(ui_Label1,"LIMIT");
      lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label1, &ui_font_VerdanaBoldItalic35, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label2 = lv_label_create(ui_Panel1);
      lv_obj_set_width( ui_Label2, 150);
      lv_obj_set_height( ui_Label2, 40);
      lv_obj_set_x( ui_Label2, -76 );
      lv_obj_set_y( ui_Label2, lv_pct(0) );
      lv_label_set_text(ui_Label2,"PESS");
      lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label2, &ui_font_VerdanaBoldItalic35, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label3 = lv_label_create(ui_Panel1);
      lv_obj_set_width( ui_Label3, 150);
      lv_obj_set_height( ui_Label3, 40);
      lv_obj_set_x( ui_Label3, -260 );
      lv_obj_set_y( ui_Label3, lv_pct(1686) );
      lv_label_set_text(ui_Label3,"PAP");
      lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label3, &ui_font_VerdanaBoldItalic35, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Panel4 = lv_obj_create(ui_PanelGauche);
      lv_obj_set_width( ui_Panel4, 131);
      lv_obj_set_height( ui_Panel4, 214);
      lv_obj_set_x( ui_Panel4, 70 );
      lv_obj_set_y( ui_Panel4, 0 );
      lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
      lv_obj_set_flex_flow(ui_Panel4,LV_FLEX_FLOW_COLUMN);
      lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
      lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      
      ui_Label1Value = lv_label_create(ui_Panel4);
      lv_obj_set_width( ui_Label1Value, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label1Value, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_Label1Value, 5 );
      lv_obj_set_y( ui_Label1Value, lv_pct(-40) );
      lv_obj_set_align( ui_Label1Value, LV_ALIGN_RIGHT_MID );
      lv_label_set_text(ui_Label1Value,"6000");
      lv_obj_set_style_text_color(ui_Label1Value, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label1Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label1Value, &ui_font_VerdanaBoldItalic45, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label2Value = lv_label_create(ui_Panel4);
      lv_obj_set_width( ui_Label2Value, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label2Value, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_align( ui_Label2Value, LV_ALIGN_RIGHT_MID );
      lv_label_set_text(ui_Label2Value,"3.1");
      lv_obj_set_style_text_color(ui_Label2Value, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label2Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label2Value, &ui_font_VerdanaBoldItalic45, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label3Value = lv_label_create(ui_Panel4);
      lv_obj_set_width( ui_Label3Value, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label3Value, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_Label3Value, 0 );
      lv_obj_set_y( ui_Label3Value, lv_pct(40) );
      lv_obj_set_align( ui_Label3Value, LV_ALIGN_RIGHT_MID );
      lv_label_set_text(ui_Label3Value,"100");
      lv_obj_set_style_text_color(ui_Label3Value, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label3Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label3Value, &ui_font_VerdanaBoldItalic45, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_PanelCentre = lv_obj_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_PanelCentre, 367);
      lv_obj_set_height( ui_PanelCentre, 290);
      lv_obj_set_x( ui_PanelCentre, 330 );
      lv_obj_set_y( ui_PanelCentre, -16 );
      lv_obj_set_align( ui_PanelCentre, LV_ALIGN_BOTTOM_LEFT );
      lv_obj_clear_flag( ui_PanelCentre, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_radius(ui_PanelCentre, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_PanelCentre, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_PanelCentre, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_PanelCentre, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_border_opa(ui_PanelCentre, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_width(ui_PanelCentre, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label4 = lv_label_create(ui_PanelCentre);
      lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_Label4, -10 );
      lv_obj_set_y( ui_Label4, -12 );
      lv_label_set_text(ui_Label4,"TEAU");
      lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label4, &ui_font_VerdanaBoldItalic45, LV_PART_MAIN| LV_STATE_DEFAULT);
      
      ui_Label5 = lv_label_create(ui_PanelCentre);
      lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_Label5, -10 );
      lv_obj_set_y( ui_Label5, 130 );
      lv_label_set_text(ui_Label5,"POIL");
      lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label5, &ui_font_VerdanaBoldItalic45, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label4Value = lv_label_create(ui_PanelCentre);
      lv_obj_set_width( ui_Label4Value, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label4Value, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_Label4Value, 0 );
      lv_obj_set_y( ui_Label4Value, 32 );
      lv_obj_set_align( ui_Label4Value, LV_ALIGN_TOP_MID );
      lv_label_set_text(ui_Label4Value,"103");
      lv_obj_set_style_text_color(ui_Label4Value, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label4Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label4Value, &ui_font_VerdanaBoldItalic90, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label5Value = lv_label_create(ui_PanelCentre);
      lv_obj_set_width( ui_Label5Value, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label5Value, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_Label5Value, 0 );
      lv_obj_set_y( ui_Label5Value, 175 );
      lv_obj_set_align( ui_Label5Value, LV_ALIGN_TOP_MID );
      lv_label_set_text(ui_Label5Value,"4.3");
      lv_obj_set_style_text_color(ui_Label5Value, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label5Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label5Value, &ui_font_VerdanaBoldItalic90, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_PanelDroiteHaut = lv_obj_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_PanelDroiteHaut, 289);
      lv_obj_set_height( ui_PanelDroiteHaut, 139);
      lv_obj_set_x( ui_PanelDroiteHaut, 719 );
      lv_obj_set_y( ui_PanelDroiteHaut, -169 );
      lv_obj_set_align( ui_PanelDroiteHaut, LV_ALIGN_BOTTOM_LEFT );
      lv_obj_clear_flag( ui_PanelDroiteHaut, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_radius(ui_PanelDroiteHaut, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_PanelDroiteHaut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_PanelDroiteHaut, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_PanelDroiteHaut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_border_opa(ui_PanelDroiteHaut, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_width(ui_PanelDroiteHaut, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label6 = lv_label_create(ui_PanelDroiteHaut);
      lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_Label6, -6 );
      lv_obj_set_y( ui_Label6, lv_pct(-42) );
      lv_obj_set_align( ui_Label6, LV_ALIGN_LEFT_MID );
      lv_label_set_text(ui_Label6,"TOIL");
      lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label6, &ui_font_VerdanaBoldItalic40, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label6Value = lv_label_create(ui_PanelDroiteHaut);
      lv_obj_set_width( ui_Label6Value, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label6Value, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_Label6Value, 0 );
      lv_obj_set_y( ui_Label6Value, lv_pct(36) );
      lv_obj_set_align( ui_Label6Value, LV_ALIGN_TOP_MID );
      lv_label_set_text(ui_Label6Value,"101");
      lv_obj_set_style_text_color(ui_Label6Value, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label6Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label6Value, &ui_font_VerdanaBoldItalic75, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_PanelDroiteBas = lv_obj_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_PanelDroiteBas, 289);
      lv_obj_set_height( ui_PanelDroiteBas, 139);
      lv_obj_set_x( ui_PanelDroiteBas, 719 );
      lv_obj_set_y( ui_PanelDroiteBas, -15 );
      lv_obj_set_align( ui_PanelDroiteBas, LV_ALIGN_BOTTOM_LEFT );
      lv_obj_clear_flag( ui_PanelDroiteBas, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_radius(ui_PanelDroiteBas, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_PanelDroiteBas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_PanelDroiteBas, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_PanelDroiteBas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_border_opa(ui_PanelDroiteBas, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_width(ui_PanelDroiteBas, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label7 = lv_label_create(ui_PanelDroiteBas);
      lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_Label7, -6 );
      lv_obj_set_y( ui_Label7, lv_pct(-42) );
      lv_obj_set_align( ui_Label7, LV_ALIGN_LEFT_MID );
      lv_label_set_text(ui_Label7,"BATT");
      lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label7, &ui_font_VerdanaBoldItalic40, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_Label7Value = lv_label_create(ui_PanelDroiteBas);
      lv_obj_set_width( ui_Label7Value, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_Label7Value, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_Label7Value, 0 );
      lv_obj_set_y( ui_Label7Value, lv_pct(35) );
      lv_obj_set_align( ui_Label7Value, LV_ALIGN_TOP_MID );
      lv_label_set_text(ui_Label7Value,"13.7");
      lv_obj_set_style_text_color(ui_Label7Value, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_Label7Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_Label7Value, &ui_font_VerdanaBoldItalic75, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_LabelRPM = lv_label_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_LabelRPM, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_LabelRPM, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_LabelRPM, 458 );
      lv_obj_set_y( ui_LabelRPM, -74 );
      lv_obj_set_align( ui_LabelRPM, LV_ALIGN_CENTER );
      lv_label_set_text(ui_LabelRPM,"RPM");
      lv_obj_set_style_text_font(ui_LabelRPM, &ui_font_VerdanaBoldItalic30, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_LabelRPMValue = lv_label_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_LabelRPMValue, 210);
      lv_obj_set_height( ui_LabelRPMValue, 58);
      lv_obj_set_x( ui_LabelRPMValue, -98 );
      lv_obj_set_y( ui_LabelRPMValue, -64 );
      lv_obj_set_align( ui_LabelRPMValue, LV_ALIGN_RIGHT_MID );
      lv_label_set_long_mode(ui_LabelRPMValue,LV_LABEL_LONG_CLIP);
      lv_label_set_text(ui_LabelRPMValue,"6750");
      lv_obj_clear_flag( ui_LabelRPMValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
      lv_obj_set_style_text_color(ui_LabelRPMValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_text_opa(ui_LabelRPMValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_align(ui_LabelRPMValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_LabelRPMValue, &ui_font_VerdanaBoldItalic75, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_BarFirstPart = lv_bar_create(ui_ScreenDisplayRX);
      lv_bar_set_value(ui_BarFirstPart,50,LV_ANIM_OFF);
      lv_bar_set_start_value(ui_BarFirstPart, 0, LV_ANIM_OFF);
      lv_obj_set_width( ui_BarFirstPart, 300);
      lv_obj_set_height( ui_BarFirstPart, 300);
      lv_obj_set_x( ui_BarFirstPart, 12 );
      lv_obj_set_y( ui_BarFirstPart, 19 );
      lv_obj_set_style_radius(ui_BarFirstPart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_BarFirstPart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_BarFirstPart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_img_src( ui_BarFirstPart, &ui_img_gauchefond_9000_png, LV_PART_MAIN | LV_STATE_DEFAULT );

      lv_obj_set_style_radius(ui_BarFirstPart, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_BarFirstPart, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_BarFirstPart, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_img_src( ui_BarFirstPart, &ui_img_gauchecurseur_9000_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

      ui_BarSecondPart = lv_bar_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_BarSecondPart, 700);
      lv_obj_set_height( ui_BarSecondPart, 160);
      lv_obj_set_x( ui_BarSecondPart, 312 );
      lv_obj_set_y( ui_BarSecondPart, 21 );
      lv_obj_set_style_radius(ui_BarSecondPart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_BarSecondPart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_BarSecondPart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_img_src( ui_BarSecondPart, &ui_img_droitefond_9000_png, LV_PART_MAIN | LV_STATE_DEFAULT );

      lv_obj_set_style_radius(ui_BarSecondPart, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_BarSecondPart, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_BarSecondPart, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_img_src( ui_BarSecondPart, &ui_img_droitecurseur_9000_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

      ui_ButtonHome = lv_btn_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_ButtonHome, 62);
      lv_obj_set_height( ui_ButtonHome, 52);
      lv_obj_set_x( ui_ButtonHome, 12 );
      lv_obj_set_y( ui_ButtonHome, 12 );
      lv_obj_add_flag( ui_ButtonHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
      lv_obj_clear_flag( ui_ButtonHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_radius(ui_ButtonHome, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_ButtonHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_ButtonHome, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_img_src( ui_ButtonHome, &ui_img_btn_menu_png, LV_PART_MAIN | LV_STATE_DEFAULT );

      ui_Horloge = lv_obj_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_Horloge, 140);
      lv_obj_set_height( ui_Horloge, 45);
      lv_obj_set_x( ui_Horloge, -363 );
      lv_obj_set_y( ui_Horloge, -262 );
      lv_obj_set_align( ui_Horloge, LV_ALIGN_CENTER );
      lv_obj_set_flex_flow(ui_Horloge,LV_FLEX_FLOW_ROW);
      lv_obj_set_flex_align(ui_Horloge, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
      lv_obj_clear_flag( ui_Horloge, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_radius(ui_Horloge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_Horloge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_Horloge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_border_color(ui_Horloge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_border_opa(ui_Horloge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_LabelHeure = lv_label_create(ui_Horloge);
      lv_obj_set_width( ui_LabelHeure, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_LabelHeure, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_LabelHeure, -51 );
      lv_obj_set_y( ui_LabelHeure, -2 );
      lv_obj_set_align( ui_LabelHeure, LV_ALIGN_CENTER );
      lv_label_set_text(ui_LabelHeure,"15");
      lv_obj_set_style_text_font(ui_LabelHeure, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_LabelSepHeureMin = lv_label_create(ui_Horloge);
      lv_obj_set_width( ui_LabelSepHeureMin, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_LabelSepHeureMin, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_LabelSepHeureMin, -13 );
      lv_obj_set_y( ui_LabelSepHeureMin, -7 );
      lv_obj_set_align( ui_LabelSepHeureMin, LV_ALIGN_CENTER );
      lv_label_set_text(ui_LabelSepHeureMin,":");
      lv_obj_set_style_text_font(ui_LabelSepHeureMin, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_LabelMin = lv_label_create(ui_Horloge);
      lv_obj_set_width( ui_LabelMin, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_LabelMin, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_x( ui_LabelMin, 29 );
      lv_obj_set_y( ui_LabelMin, -1 );
      lv_obj_set_align( ui_LabelMin, LV_ALIGN_CENTER );
      lv_label_set_text(ui_LabelMin,"35");
      lv_obj_set_style_text_font(ui_LabelMin, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_ALERTETEAU = lv_obj_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_ALERTETEAU, lv_pct(75));
      lv_obj_set_height( ui_ALERTETEAU, lv_pct(75));
      lv_obj_set_align( ui_ALERTETEAU, LV_ALIGN_CENTER );
      lv_obj_add_flag( ui_ALERTETEAU, LV_OBJ_FLAG_HIDDEN );   /// Flags
      lv_obj_clear_flag( ui_ALERTETEAU, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_radius(ui_ALERTETEAU, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_ALERTETEAU, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_ALERTETEAU, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

      ui_LabelAlerteEau = lv_label_create(ui_ALERTETEAU);
      lv_obj_set_width( ui_LabelAlerteEau, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_LabelAlerteEau, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_align( ui_LabelAlerteEau, LV_ALIGN_CENTER );
      lv_label_set_text(ui_LabelAlerteEau,"ALERTE\nTEMP. EAU");
      lv_obj_clear_flag( ui_LabelAlerteEau, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
      lv_obj_set_style_text_align(ui_LabelAlerteEau, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_LabelAlerteEau, &ui_font_VerdanaBoldItalic75, LV_PART_MAIN| LV_STATE_DEFAULT);
      
      ui_ALERTEPOIL = lv_obj_create(ui_ScreenDisplayRX);
      lv_obj_set_width( ui_ALERTEPOIL, lv_pct(75));
      lv_obj_set_height( ui_ALERTEPOIL, lv_pct(75));
      lv_obj_set_align( ui_ALERTEPOIL, LV_ALIGN_CENTER );
      lv_obj_add_flag( ui_ALERTEPOIL, LV_OBJ_FLAG_HIDDEN );   /// Flags
      lv_obj_clear_flag( ui_ALERTEPOIL, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
      lv_obj_set_style_radius(ui_ALERTEPOIL, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_bg_color(ui_ALERTEPOIL, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
      lv_obj_set_style_bg_opa(ui_ALERTEPOIL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
      
      ui_LabelAlerteOil = lv_label_create(ui_ALERTEPOIL);
      lv_obj_set_width( ui_LabelAlerteOil, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height( ui_LabelAlerteOil, LV_SIZE_CONTENT);   /// 1
      lv_obj_set_align( ui_LabelAlerteOil, LV_ALIGN_CENTER );
      lv_label_set_text(ui_LabelAlerteOil,"ALERTE\nPRESSION HUILE");
      lv_obj_clear_flag( ui_LabelAlerteOil, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
      lv_obj_set_style_text_align(ui_LabelAlerteOil, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_LabelAlerteOil, &ui_font_VerdanaBoldItalic75, LV_PART_MAIN| LV_STATE_DEFAULT);

      lv_obj_add_event_cb(ui_ButtonHome, ui_event_ButtonHome, LV_EVENT_ALL, NULL);
      lv_obj_add_event_cb(ui_ScreenDisplayRX, ui_event_ScreenDisplayRX, LV_EVENT_ALL, NULL);
      uic_PanelGauche = ui_PanelGauche;
      uic_Panel1 = ui_Panel1;
      uic_Label1 = ui_Label1;
      uic_Label2 = ui_Label2;
      uic_Label3 = ui_Label3;
      uic_Panel4 = ui_Panel4;
      uic_Label1Value = ui_Label1Value;
      uic_Label2Value = ui_Label2Value;
      uic_Label3Value = ui_Label3Value;
      uic_PanelCentre = ui_PanelCentre;
      uic_Label4 = ui_Label4;
      uic_Label5 = ui_Label5;
      uic_Label4Value = ui_Label4Value;
      uic_Label5Value = ui_Label5Value;
      uic_PanelDroiteHaut = ui_PanelDroiteHaut;
      uic_Label6 = ui_Label6;
      uic_Label6Value = ui_Label6Value;
      uic_PanelDroiteBas = ui_PanelDroiteBas;
      uic_Label7 = ui_Label7;
      uic_Label7Value = ui_Label7Value;
      uic_LabelRPM = ui_LabelRPM;
      uic_LabelRPMValue = ui_LabelRPMValue;
      uic_BarFirstPart = ui_BarFirstPart;
      uic_BarSecondPart = ui_BarSecondPart;
      uic_ButtonHome = ui_ButtonHome;
      uic_Horloge = ui_Horloge;
      uic_LabelHeure = ui_LabelHeure;
      uic_LabelSepHeureMin = ui_LabelSepHeureMin;
      uic_LabelMin = ui_LabelMin;
      uic_ALERTETEAU = ui_ALERTETEAU;
      uic_LabelAlerteEau = ui_LabelAlerteEau;
      uic_ALERTEPOIL = ui_ALERTEPOIL;
      uic_LabelAlerteOil = ui_LabelAlerteOil;

}

void ui_ScreenDisplayRX_screen_destroy(void)
{
      if (ui_ScreenDisplayRX) lv_obj_del(ui_ScreenDisplayRX);

      // NULL screen variables
      ui_ScreenDisplayRX= NULL;
      uic_PanelGauche= NULL;
      ui_PanelGauche= NULL;
      uic_Panel1= NULL;
      ui_Panel1= NULL;
      uic_Label1= NULL;
      ui_Label1= NULL;
      uic_Label2= NULL;
      ui_Label2= NULL;
      uic_Label3= NULL;
      ui_Label3= NULL;
      uic_Panel4= NULL;
      ui_Panel4= NULL;
      uic_Label1Value= NULL;
      ui_Label1Value= NULL;
      uic_Label2Value= NULL;
      ui_Label2Value= NULL;
      uic_Label3Value= NULL;
      ui_Label3Value= NULL;
      uic_PanelCentre= NULL;
      ui_PanelCentre= NULL;
      uic_Label4= NULL;
      ui_Label4= NULL;
      uic_Label5= NULL;
      ui_Label5= NULL;
      uic_Label4Value= NULL;
      ui_Label4Value= NULL;
      uic_Label5Value= NULL;
      ui_Label5Value= NULL;
      uic_PanelDroiteHaut= NULL;
      ui_PanelDroiteHaut= NULL;
      uic_Label6= NULL;
      ui_Label6= NULL;
      uic_Label6Value= NULL;
      ui_Label6Value= NULL;
      uic_PanelDroiteBas= NULL;
      ui_PanelDroiteBas= NULL;
      uic_Label7= NULL;
      ui_Label7= NULL;
      uic_Label7Value= NULL;
      ui_Label7Value= NULL;
      uic_LabelRPM= NULL;
      ui_LabelRPM= NULL;
      uic_LabelRPMValue= NULL;
      ui_LabelRPMValue= NULL;
      uic_BarFirstPart= NULL;
      ui_BarFirstPart= NULL;
      uic_BarSecondPart= NULL;
      ui_BarSecondPart= NULL;
      uic_ButtonHome= NULL;
      ui_ButtonHome= NULL;
      uic_Horloge= NULL;
      ui_Horloge= NULL;
      uic_LabelHeure= NULL;
      ui_LabelHeure= NULL;
      uic_LabelSepHeureMin= NULL;
      ui_LabelSepHeureMin= NULL;
      uic_LabelMin= NULL;
      ui_LabelMin= NULL;
      uic_ALERTETEAU= NULL;
      ui_ALERTETEAU= NULL;
      uic_LabelAlerteEau= NULL;
      ui_LabelAlerteEau= NULL;
      uic_ALERTEPOIL= NULL;
      ui_ALERTEPOIL= NULL;
      uic_LabelAlerteOil= NULL;
      ui_LabelAlerteOil= NULL;
}
