// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#include "../ui_manager.h"

lv_obj_t *uic_LabelAlerteOil1;
lv_obj_t *uic_ALERTEPOIL1;
lv_obj_t *uic_LabelAlerteEau1;
lv_obj_t *uic_ALERTETEAU1;
lv_obj_t *uic_LabelRapportBV;
lv_obj_t *uic_ImageCadreRapportBV;
lv_obj_t *uic_LabelMin1;
lv_obj_t *uic_LabelSepHeureMin1;
lv_obj_t *uic_LabelHeure1;
lv_obj_t *uic_Horloge1;
lv_obj_t *uic_ButtonHome3;
lv_obj_t *uic_BarSecondPart1;
lv_obj_t *uic_BarFirstPart1;
lv_obj_t *uic_LabelRPMValue1;
lv_obj_t *uic_LabelRPM1;
lv_obj_t *uic_Dropdown5;
lv_obj_t *uic_Label7Value1;
lv_obj_t *uic_PanelDroiteBas1;
lv_obj_t *uic_Dropdown4;
lv_obj_t *uic_Label6Value1;
lv_obj_t *uic_PanelDroiteHaut1;
lv_obj_t *uic_Dropdown3;
lv_obj_t *uic_Dropdown2;
lv_obj_t *uic_Dropdown1;
lv_obj_t *uic_Panel2;
lv_obj_t *uic_Label3Value1;
lv_obj_t *uic_Label2Value1;
lv_obj_t *uic_Label1Value1;
lv_obj_t *uic_Panel3;
lv_obj_t *uic_PanelGauche1;
lv_obj_t *ui_ScreenDisplayBV = NULL;lv_obj_t *ui_PanelGauche1 = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Label1Value1 = NULL;lv_obj_t *ui_Label2Value1 = NULL;lv_obj_t *ui_Label3Value1 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Dropdown1 = NULL;lv_obj_t *ui_Dropdown2 = NULL;lv_obj_t *ui_Dropdown3 = NULL;lv_obj_t *ui_PanelDroiteHaut1 = NULL;lv_obj_t *ui_Label6Value1 = NULL;lv_obj_t *ui_Dropdown4 = NULL;lv_obj_t *ui_PanelDroiteBas1 = NULL;lv_obj_t *ui_Label7Value1 = NULL;lv_obj_t *ui_Dropdown5 = NULL;lv_obj_t *ui_LabelRPM1 = NULL;lv_obj_t *ui_LabelRPMValue1 = NULL;lv_obj_t *ui_BarFirstPart1 = NULL;lv_obj_t *ui_BarSecondPart1 = NULL;lv_obj_t *ui_ButtonHome3 = NULL;lv_obj_t *ui_Horloge1 = NULL;lv_obj_t *ui_LabelHeure1 = NULL;lv_obj_t *ui_LabelSepHeureMin1 = NULL;lv_obj_t *ui_LabelMin1 = NULL;lv_obj_t *ui_ImageCadreRapportBV = NULL;lv_obj_t *ui_LabelRapportBV = NULL;lv_obj_t *ui_ALERTETEAU1 = NULL;lv_obj_t *ui_LabelAlerteEau1 = NULL;lv_obj_t *ui_ALERTEPOIL1 = NULL;lv_obj_t *ui_LabelAlerteOil1 = NULL;
// event funtions
void ui_event_ScreenDisplayBV( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ScreenDisplayRX, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenDisplayRX_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ScreenDisplayRX, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenDisplayRX_screen_init);
}
}

void ui_event_ButtonHome3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMenu_screen_init);
}
}

// build funtions

void ui_ScreenDisplayBV_screen_init(void)
{
ui_ScreenDisplayBV = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenDisplayBV, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_ScreenDisplayBV, &ui_img_gddash_70_fond_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_PanelGauche1 = lv_obj_create(ui_ScreenDisplayBV);
lv_obj_set_width( ui_PanelGauche1, 337);
lv_obj_set_height( ui_PanelGauche1, 226);
lv_obj_set_x( ui_PanelGauche1, 18 );
lv_obj_set_y( ui_PanelGauche1, -16 );
lv_obj_set_align( ui_PanelGauche1, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_PanelGauche1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelGauche1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelGauche1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelGauche1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelGauche1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelGauche1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelGauche1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_PanelGauche1);
lv_obj_set_width( ui_Panel3, 131);
lv_obj_set_height( ui_Panel3, 214);
lv_obj_set_x( ui_Panel3, 76 );
lv_obj_set_y( ui_Panel3, 0 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1Value1 = lv_label_create(ui_Panel3);
lv_obj_set_height( ui_Label1Value1, 40);
lv_obj_set_width( ui_Label1Value1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Label1Value1, -23 );
lv_obj_set_y( ui_Label1Value1, lv_pct(-46) );
lv_obj_set_align( ui_Label1Value1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label1Value1,"6000");
lv_obj_set_style_text_color(ui_Label1Value1, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1Value1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1Value1, &ui_font_VerdanaBoldItalic45, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2Value1 = lv_label_create(ui_Panel3);
lv_obj_set_height( ui_Label2Value1, 40);
lv_obj_set_width( ui_Label2Value1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Label2Value1, -4 );
lv_obj_set_y( ui_Label2Value1, lv_pct(-3) );
lv_obj_set_align( ui_Label2Value1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label2Value1,"3.1");
lv_obj_set_style_text_color(ui_Label2Value1, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2Value1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2Value1, &ui_font_VerdanaBoldItalic45, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3Value1 = lv_label_create(ui_Panel3);
lv_obj_set_height( ui_Label3Value1, 40);
lv_obj_set_width( ui_Label3Value1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Label3Value1, -17 );
lv_obj_set_y( ui_Label3Value1, lv_pct(39) );
lv_obj_set_align( ui_Label3Value1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label3Value1,"100");
lv_obj_set_style_text_color(ui_Label3Value1, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3Value1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3Value1, &ui_font_VerdanaBoldItalic45, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_PanelGauche1);
lv_obj_set_width( ui_Panel2, 150);
lv_obj_set_height( ui_Panel2, 214);
lv_obj_set_x( ui_Panel2, -76 );
lv_obj_set_y( ui_Panel2, 0 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown1 = lv_dropdown_create(ui_Panel2);
lv_dropdown_set_dir( ui_Dropdown1, LV_DIR_RIGHT);
lv_dropdown_set_options( ui_Dropdown1, "LIMIT\nPOIL\nTOIL\nTEAU\nPAP\nBATT\nTOIL" );
lv_obj_set_width( ui_Dropdown1, 150);
lv_obj_set_height( ui_Dropdown1, 40);
lv_obj_set_x( ui_Dropdown1, -22 );
lv_obj_set_y( ui_Dropdown1, -75 );
lv_obj_clear_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_Dropdown1, &ui_font_VerdanaBoldItalic35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Dropdown1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Dropdown1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Dropdown1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Dropdown1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Dropdown1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dropdown1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dropdown1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dropdown1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Dropdown1, lv_color_hex(0xDE09DE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Dropdown1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown1), &lv_font_montserrat_30,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown2 = lv_dropdown_create(ui_Panel2);
lv_dropdown_set_dir( ui_Dropdown2, LV_DIR_RIGHT);
lv_dropdown_set_options( ui_Dropdown2, "LIMIT\nPOIL\nTOIL\nTEAU\nPAP\nBATT\nTOIL" );
lv_obj_set_width( ui_Dropdown2, 150);
lv_obj_set_height( ui_Dropdown2, 40);
lv_obj_set_x( ui_Dropdown2, -20 );
lv_obj_set_y( ui_Dropdown2, 62 );
lv_obj_clear_flag( ui_Dropdown2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_Dropdown2, &ui_font_VerdanaBoldItalic35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Dropdown2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Dropdown2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Dropdown2, lv_color_hex(0xDE09DE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Dropdown2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown2), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown2), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown2), &lv_font_montserrat_30,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown2), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown2), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown3 = lv_dropdown_create(ui_Panel2);
lv_dropdown_set_dir( ui_Dropdown3, LV_DIR_RIGHT);
lv_dropdown_set_options( ui_Dropdown3, "LIMIT\nPOIL\nTOIL\nTEAU\nPAP\nBATT\nTOIL" );
lv_obj_set_width( ui_Dropdown3, 150);
lv_obj_set_height( ui_Dropdown3, 40);
lv_obj_set_x( ui_Dropdown3, -20 );
lv_obj_set_y( ui_Dropdown3, 127 );
lv_obj_clear_flag( ui_Dropdown3, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_Dropdown3, &ui_font_VerdanaBoldItalic35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Dropdown3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Dropdown3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Dropdown3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Dropdown3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Dropdown3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dropdown3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dropdown3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dropdown3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Dropdown3, lv_color_hex(0xDE09DE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Dropdown3, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown3), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown3), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown3), &lv_font_montserrat_30,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown3), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown3), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelDroiteHaut1 = lv_obj_create(ui_ScreenDisplayBV);
lv_obj_set_width( ui_PanelDroiteHaut1, 338);
lv_obj_set_height( ui_PanelDroiteHaut1, 139);
lv_obj_set_x( ui_PanelDroiteHaut1, 669 );
lv_obj_set_y( ui_PanelDroiteHaut1, -173 );
lv_obj_set_align( ui_PanelDroiteHaut1, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_PanelDroiteHaut1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelDroiteHaut1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelDroiteHaut1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelDroiteHaut1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelDroiteHaut1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelDroiteHaut1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelDroiteHaut1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6Value1 = lv_label_create(ui_PanelDroiteHaut1);
lv_obj_set_width( ui_Label6Value1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6Value1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6Value1, 0 );
lv_obj_set_y( ui_Label6Value1, lv_pct(36) );
lv_obj_set_align( ui_Label6Value1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label6Value1,"101");
lv_obj_set_style_text_color(ui_Label6Value1, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6Value1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6Value1, &ui_font_VerdanaBoldItalic75, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown4 = lv_dropdown_create(ui_PanelDroiteHaut1);
lv_dropdown_set_dir( ui_Dropdown4, LV_DIR_RIGHT);
lv_dropdown_set_options( ui_Dropdown4, "LIMIT\nPOIL\nTOIL\nTEAU\nPAP\nBATT\nTOIL" );
lv_obj_set_width( ui_Dropdown4, 150);
lv_obj_set_height( ui_Dropdown4, 40);
lv_obj_set_x( ui_Dropdown4, -6 );
lv_obj_set_y( ui_Dropdown4, lv_pct(-42) );
lv_obj_set_align( ui_Dropdown4, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Dropdown4, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_Dropdown4, &ui_font_VerdanaBoldItalic40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Dropdown4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Dropdown4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Dropdown4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Dropdown4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Dropdown4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dropdown4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dropdown4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dropdown4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Dropdown4, lv_color_hex(0xDE09DE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Dropdown4, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown4), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown4), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown4), &lv_font_montserrat_30,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown4), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown4), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelDroiteBas1 = lv_obj_create(ui_ScreenDisplayBV);
lv_obj_set_width( ui_PanelDroiteBas1, 331);
lv_obj_set_height( ui_PanelDroiteBas1, 139);
lv_obj_set_x( ui_PanelDroiteBas1, 672 );
lv_obj_set_y( ui_PanelDroiteBas1, -20 );
lv_obj_set_align( ui_PanelDroiteBas1, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_PanelDroiteBas1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelDroiteBas1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelDroiteBas1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelDroiteBas1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelDroiteBas1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelDroiteBas1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelDroiteBas1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7Value1 = lv_label_create(ui_PanelDroiteBas1);
lv_obj_set_width( ui_Label7Value1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7Value1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7Value1, 0 );
lv_obj_set_y( ui_Label7Value1, lv_pct(35) );
lv_obj_set_align( ui_Label7Value1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label7Value1,"13.7");
lv_obj_set_style_text_color(ui_Label7Value1, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7Value1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7Value1, &ui_font_VerdanaBoldItalic75, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown5 = lv_dropdown_create(ui_PanelDroiteBas1);
lv_dropdown_set_dir( ui_Dropdown5, LV_DIR_RIGHT);
lv_dropdown_set_options( ui_Dropdown5, "LIMIT\nPOIL\nTOIL\nTEAU\nPAP\nBATT\nTOIL" );
lv_obj_set_width( ui_Dropdown5, 150);
lv_obj_set_height( ui_Dropdown5, 40);
lv_obj_set_x( ui_Dropdown5, -6 );
lv_obj_set_y( ui_Dropdown5, lv_pct(-42) );
lv_obj_set_align( ui_Dropdown5, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Dropdown5, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_Dropdown5, &ui_font_VerdanaBoldItalic40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Dropdown5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Dropdown5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Dropdown5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Dropdown5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Dropdown5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dropdown5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dropdown5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dropdown5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Dropdown5, lv_color_hex(0xDE09DE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Dropdown5, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown5), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown5), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown5), &lv_font_montserrat_30,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown5), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown5), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelRPM1 = lv_label_create(ui_ScreenDisplayBV);
lv_obj_set_width( ui_LabelRPM1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRPM1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelRPM1, 458 );
lv_obj_set_y( ui_LabelRPM1, -74 );
lv_obj_set_align( ui_LabelRPM1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelRPM1,"RPM");
lv_obj_set_style_text_font(ui_LabelRPM1, &ui_font_VerdanaBoldItalic30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelRPMValue1 = lv_label_create(ui_ScreenDisplayBV);
lv_obj_set_width( ui_LabelRPMValue1, 210);
lv_obj_set_height( ui_LabelRPMValue1, 57);
lv_obj_set_x( ui_LabelRPMValue1, -98 );
lv_obj_set_y( ui_LabelRPMValue1, -64 );
lv_obj_set_align( ui_LabelRPMValue1, LV_ALIGN_RIGHT_MID );
lv_label_set_long_mode(ui_LabelRPMValue1,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_LabelRPMValue1,"6750");
lv_obj_clear_flag( ui_LabelRPMValue1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelRPMValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelRPMValue1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelRPMValue1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelRPMValue1, &ui_font_VerdanaBoldItalic75, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarFirstPart1 = lv_bar_create(ui_ScreenDisplayBV);
lv_bar_set_value(ui_BarFirstPart1,50,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarFirstPart1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarFirstPart1, 300);
lv_obj_set_height( ui_BarFirstPart1, 300);
lv_obj_set_x( ui_BarFirstPart1, 12 );
lv_obj_set_y( ui_BarFirstPart1, 19 );
lv_obj_set_style_radius(ui_BarFirstPart1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarFirstPart1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarFirstPart1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_BarFirstPart1, &ui_img_gauchefond_9000_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_BarFirstPart1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarFirstPart1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarFirstPart1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_BarFirstPart1, &ui_img_gauchecurseur_9000_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

ui_BarSecondPart1 = lv_bar_create(ui_ScreenDisplayBV);
lv_obj_set_width( ui_BarSecondPart1, 700);
lv_obj_set_height( ui_BarSecondPart1, 160);
lv_obj_set_x( ui_BarSecondPart1, 312 );
lv_obj_set_y( ui_BarSecondPart1, 21 );
lv_obj_set_style_radius(ui_BarSecondPart1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarSecondPart1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarSecondPart1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_BarSecondPart1, &ui_img_droitefond_9000_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_BarSecondPart1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarSecondPart1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarSecondPart1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_BarSecondPart1, &ui_img_droitecurseur_9000_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

ui_ButtonHome3 = lv_btn_create(ui_ScreenDisplayBV);
lv_obj_set_width( ui_ButtonHome3, 62);
lv_obj_set_height( ui_ButtonHome3, 52);
lv_obj_set_x( ui_ButtonHome3, 12 );
lv_obj_set_y( ui_ButtonHome3, 12 );
lv_obj_add_flag( ui_ButtonHome3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonHome3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonHome3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonHome3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonHome3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ButtonHome3, &ui_img_btn_menu_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Horloge1 = lv_obj_create(ui_ScreenDisplayBV);
lv_obj_set_width( ui_Horloge1, 140);
lv_obj_set_height( ui_Horloge1, 45);
lv_obj_set_x( ui_Horloge1, -363 );
lv_obj_set_y( ui_Horloge1, -262 );
lv_obj_set_align( ui_Horloge1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Horloge1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Horloge1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Horloge1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Horloge1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Horloge1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Horloge1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Horloge1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Horloge1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHeure1 = lv_label_create(ui_Horloge1);
lv_obj_set_width( ui_LabelHeure1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHeure1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHeure1, -51 );
lv_obj_set_y( ui_LabelHeure1, -2 );
lv_obj_set_align( ui_LabelHeure1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHeure1,"15");
lv_obj_set_style_text_font(ui_LabelHeure1, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSepHeureMin1 = lv_label_create(ui_Horloge1);
lv_obj_set_width( ui_LabelSepHeureMin1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSepHeureMin1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSepHeureMin1, -13 );
lv_obj_set_y( ui_LabelSepHeureMin1, -7 );
lv_obj_set_align( ui_LabelSepHeureMin1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSepHeureMin1,":");
lv_obj_set_style_text_font(ui_LabelSepHeureMin1, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMin1 = lv_label_create(ui_Horloge1);
lv_obj_set_width( ui_LabelMin1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMin1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMin1, 30 );
lv_obj_set_y( ui_LabelMin1, -1 );
lv_obj_set_align( ui_LabelMin1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMin1,"35");
lv_obj_set_style_text_font(ui_LabelMin1, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageCadreRapportBV = lv_img_create(ui_ScreenDisplayBV);
lv_img_set_src(ui_ImageCadreRapportBV, &ui_img_1361701724);
lv_obj_set_width( ui_ImageCadreRapportBV, 274);
lv_obj_set_height( ui_ImageCadreRapportBV, 375);
lv_obj_set_x( ui_ImageCadreRapportBV, 0 );
lv_obj_set_y( ui_ImageCadreRapportBV, 95 );
lv_obj_set_align( ui_ImageCadreRapportBV, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImageCadreRapportBV, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ImageCadreRapportBV, LV_SCROLLBAR_MODE_OFF);

ui_LabelRapportBV = lv_label_create(ui_ImageCadreRapportBV);
lv_obj_set_width( ui_LabelRapportBV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRapportBV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelRapportBV, 3 );
lv_obj_set_y( ui_LabelRapportBV, 0 );
lv_obj_set_align( ui_LabelRapportBV, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelRapportBV,"5");
lv_obj_set_style_text_color(ui_LabelRapportBV, lv_color_hex(0x67FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelRapportBV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelRapportBV, &ui_font_RapBV, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ALERTETEAU1 = lv_obj_create(ui_ScreenDisplayBV);
lv_obj_set_width( ui_ALERTETEAU1, lv_pct(75));
lv_obj_set_height( ui_ALERTETEAU1, lv_pct(75));
lv_obj_set_align( ui_ALERTETEAU1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ALERTETEAU1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_ALERTETEAU1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ALERTETEAU1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ALERTETEAU1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ALERTETEAU1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAlerteEau1 = lv_label_create(ui_ALERTETEAU1);
lv_obj_set_width( ui_LabelAlerteEau1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAlerteEau1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelAlerteEau1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAlerteEau1,"ALERTE\nTEMP. EAU");
lv_obj_clear_flag( ui_LabelAlerteEau1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_align(ui_LabelAlerteEau1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelAlerteEau1, &ui_font_VerdanaBoldItalic75, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ALERTEPOIL1 = lv_obj_create(ui_ScreenDisplayBV);
lv_obj_set_width( ui_ALERTEPOIL1, lv_pct(75));
lv_obj_set_height( ui_ALERTEPOIL1, lv_pct(75));
lv_obj_set_align( ui_ALERTEPOIL1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ALERTEPOIL1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_ALERTEPOIL1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ALERTEPOIL1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ALERTEPOIL1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ALERTEPOIL1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAlerteOil1 = lv_label_create(ui_ALERTEPOIL1);
lv_obj_set_width( ui_LabelAlerteOil1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAlerteOil1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelAlerteOil1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAlerteOil1,"ALERTE\nPRESSION HUILE");
lv_obj_clear_flag( ui_LabelAlerteOil1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_align(ui_LabelAlerteOil1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelAlerteOil1, &ui_font_VerdanaBoldItalic75, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonHome3, ui_event_ButtonHome3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenDisplayBV, ui_event_ScreenDisplayBV, LV_EVENT_ALL, NULL);
uic_PanelGauche1 = ui_PanelGauche1;
uic_Panel3 = ui_Panel3;
uic_Label1Value1 = ui_Label1Value1;
uic_Label2Value1 = ui_Label2Value1;
uic_Label3Value1 = ui_Label3Value1;
uic_Panel2 = ui_Panel2;
uic_Dropdown1 = ui_Dropdown1;
uic_Dropdown2 = ui_Dropdown2;
uic_Dropdown3 = ui_Dropdown3;
uic_PanelDroiteHaut1 = ui_PanelDroiteHaut1;
uic_Label6Value1 = ui_Label6Value1;
uic_Dropdown4 = ui_Dropdown4;
uic_PanelDroiteBas1 = ui_PanelDroiteBas1;
uic_Label7Value1 = ui_Label7Value1;
uic_Dropdown5 = ui_Dropdown5;
uic_LabelRPM1 = ui_LabelRPM1;
uic_LabelRPMValue1 = ui_LabelRPMValue1;
uic_BarFirstPart1 = ui_BarFirstPart1;
uic_BarSecondPart1 = ui_BarSecondPart1;
uic_ButtonHome3 = ui_ButtonHome3;
uic_Horloge1 = ui_Horloge1;
uic_LabelHeure1 = ui_LabelHeure1;
uic_LabelSepHeureMin1 = ui_LabelSepHeureMin1;
uic_LabelMin1 = ui_LabelMin1;
uic_ImageCadreRapportBV = ui_ImageCadreRapportBV;
uic_LabelRapportBV = ui_LabelRapportBV;
uic_ALERTETEAU1 = ui_ALERTETEAU1;
uic_LabelAlerteEau1 = ui_LabelAlerteEau1;
uic_ALERTEPOIL1 = ui_ALERTEPOIL1;
uic_LabelAlerteOil1 = ui_LabelAlerteOil1;

}

void ui_ScreenDisplayBV_screen_destroy(void)
{
   if (ui_ScreenDisplayBV) lv_obj_del(ui_ScreenDisplayBV);

// NULL screen variables
ui_ScreenDisplayBV= NULL;
uic_PanelGauche1= NULL;
ui_PanelGauche1= NULL;
uic_Panel3= NULL;
ui_Panel3= NULL;
uic_Label1Value1= NULL;
ui_Label1Value1= NULL;
uic_Label2Value1= NULL;
ui_Label2Value1= NULL;
uic_Label3Value1= NULL;
ui_Label3Value1= NULL;
uic_Panel2= NULL;
ui_Panel2= NULL;
uic_Dropdown1= NULL;
ui_Dropdown1= NULL;
uic_Dropdown2= NULL;
ui_Dropdown2= NULL;
uic_Dropdown3= NULL;
ui_Dropdown3= NULL;
uic_PanelDroiteHaut1= NULL;
ui_PanelDroiteHaut1= NULL;
uic_Label6Value1= NULL;
ui_Label6Value1= NULL;
uic_Dropdown4= NULL;
ui_Dropdown4= NULL;
uic_PanelDroiteBas1= NULL;
ui_PanelDroiteBas1= NULL;
uic_Label7Value1= NULL;
ui_Label7Value1= NULL;
uic_Dropdown5= NULL;
ui_Dropdown5= NULL;
uic_LabelRPM1= NULL;
ui_LabelRPM1= NULL;
uic_LabelRPMValue1= NULL;
ui_LabelRPMValue1= NULL;
uic_BarFirstPart1= NULL;
ui_BarFirstPart1= NULL;
uic_BarSecondPart1= NULL;
ui_BarSecondPart1= NULL;
uic_ButtonHome3= NULL;
ui_ButtonHome3= NULL;
uic_Horloge1= NULL;
ui_Horloge1= NULL;
uic_LabelHeure1= NULL;
ui_LabelHeure1= NULL;
uic_LabelSepHeureMin1= NULL;
ui_LabelSepHeureMin1= NULL;
uic_LabelMin1= NULL;
ui_LabelMin1= NULL;
uic_ImageCadreRapportBV= NULL;
ui_ImageCadreRapportBV= NULL;
uic_LabelRapportBV= NULL;
ui_LabelRapportBV= NULL;
uic_ALERTETEAU1= NULL;
ui_ALERTETEAU1= NULL;
uic_LabelAlerteEau1= NULL;
ui_LabelAlerteEau1= NULL;
uic_ALERTEPOIL1= NULL;
ui_ALERTEPOIL1= NULL;
uic_LabelAlerteOil1= NULL;
ui_LabelAlerteOil1= NULL;

}
