// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_screenconfig.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_screen_config_png);   // assets/screen_config.png
LV_IMG_DECLARE( ui_img_bouton_noir_png);   // assets/bouton_noir.png
LV_IMG_DECLARE( ui_img_bouton_vert_png);   // assets/bouton_vert.png
LV_IMG_DECLARE( ui_img_bouton_orange_png);   // assets/bouton_orange.png
LV_IMG_DECLARE( ui_img_bouton_rouge_png);   // assets/bouton_rouge.png
LV_IMG_DECLARE( ui_img_bouton_cyan_png);   // assets/bouton_cyan.png
LV_IMG_DECLARE( ui_img_bouton_bleu_png);   // assets/bouton_bleu.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
