// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void set_target_led(lv_event_t * e);
void reset_led_to_black(lv_event_t * e);
void set_target_colour(lv_event_t * e);
void apply_color_green(lv_event_t * e);
void apply_color_orange(lv_event_t * e);
void apply_color_red(lv_event_t * e);
void apply_color_cyan(lv_event_t * e);
void apply_color_blue(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
