// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void set_target_led(lv_event_t * e);
void reset_led_to_black(lv_event_t * e);
void set_target_colour(lv_event_t * e);
void apply_color_green(lv_event_t * e);
void apply_color_orange(lv_event_t * e);
void apply_color_red(lv_event_t * e);
void apply_color_cyan(lv_event_t * e);
void apply_color_blue(lv_event_t * e);
void update_console_display();
void keyboard_add_digit(const char* digit);
void keyboard_backspace(lv_event_t * e);
void keyboard_dot(lv_event_t * e);
void keyboard_0(lv_event_t * e);
void keyboard_1(lv_event_t * e);
void keyboard_2(lv_event_t * e);
void keyboard_3(lv_event_t * e);
void keyboard_4(lv_event_t * e);
void keyboard_5(lv_event_t * e);
void keyboard_6(lv_event_t * e);
void keyboard_7(lv_event_t * e);
void keyboard_8(lv_event_t * e);
void keyboard_9(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
