// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.3+
// LVGL version: 8.3.11
// Project name: design

#include "ui.h"

#if !defined(UI_VARIABLE_STYLES_MODE_INIT)
#define UI_VARIABLE_STYLES_MODE_INIT 0
#endif

// --- DÉCLARATIONS EXTERNES ---
// Ces variables doivent être définies dans ui.c
extern uint8_t ui_theme_idx;
extern _ui_local_style_t* _ui_local_styles;
extern uint32_t _ui_local_style_count;

// --- DÉFINITIONS DES FONCTIONS DE CONVERSION (À PLACER EN HAUT) ---

ui_style_variable_t ui_get_theme_value(const ui_theme_variable_t* var) {
    return var[ui_theme_idx];
}

lv_style_value_t _ui_style_value_convert(lv_style_prop_t property, ui_style_variable_t value) {
    static lv_style_value_t Style_Value;
    if (property == LV_STYLE_BG_COLOR || property == LV_STYLE_BG_GRAD_COLOR || property == LV_STYLE_BG_IMG_RECOLOR || property == LV_STYLE_BORDER_COLOR
        || property == LV_STYLE_OUTLINE_COLOR || property == LV_STYLE_SHADOW_COLOR || property == LV_STYLE_IMG_RECOLOR || property == LV_STYLE_LINE_COLOR
        || property == LV_STYLE_ARC_COLOR || property == LV_STYLE_TEXT_COLOR) {
        Style_Value.color = lv_color_hex(value);
    }
    else if (property == LV_STYLE_BG_GRAD || property == LV_STYLE_BG_IMG_SRC || property == LV_STYLE_ARC_IMG_SRC || property == LV_STYLE_TEXT_FONT
             || property == LV_STYLE_COLOR_FILTER_DSC || property == LV_STYLE_ANIM || property == LV_STYLE_TRANSITION) {
        Style_Value.ptr = (void*)(uintptr_t)value;
    }
    else Style_Value.num = value;
    return Style_Value;
}

inline void ui_object_set_local_style_property
(lv_obj_t* object_p, lv_style_selector_t selector, lv_style_prop_t property, ui_style_variable_t value) {
    if (object_p != NULL) {
        lv_obj_set_local_style_prop(object_p, property, _ui_style_value_convert(property, value), selector);
    }
}

// --- GESTION DES STYLES LOCAUX ---

_ui_local_style_t* _ui_local_style_create(const ui_style_variable_t* style_variable_p, bool is_themeable) {
    static uint32_t i;
    static _ui_local_style_t* local_style_p;

    for (i = 0; i < _ui_local_style_count; ++i) {
        if (_ui_local_styles[i].style_variable_p == style_variable_p) return &_ui_local_styles[i];
    }

    _ui_local_styles = (_ui_local_style_t*)lv_mem_realloc(_ui_local_styles, (_ui_local_style_count + 1) * sizeof(_ui_local_style_t));
    LV_ASSERT_MALLOC(_ui_local_styles);
    if (_ui_local_styles == NULL) return NULL;

    local_style_p = &_ui_local_styles[_ui_local_style_count];
    local_style_p->style_variable_p = (ui_style_variable_t*)style_variable_p;
    local_style_p->is_themeable = is_themeable;
    local_style_p->previous_pointer = NULL;
    local_style_p->previous_value = -1;
    local_style_p->style_property_setting_count = 0;
    local_style_p->style_property_settings = NULL;

    ++_ui_local_style_count;
    return local_style_p;
}

void _ui_local_style_property_setting_delete(lv_event_t* event) {
    lv_obj_t** ptr = (lv_obj_t**)lv_event_get_user_data(event);
    if (ptr) *ptr = NULL;
}

_ui_local_style_property_setting_t* _ui_local_style_property_setting_create
(_ui_local_style_t* local_style_p, lv_obj_t* object_p, lv_style_selector_t selector, lv_style_prop_t property) {
    static uint32_t i;
    static _ui_local_style_property_setting_t *style_property_setting_p, *empty_style_property_setting_p;

    style_property_setting_p = (_ui_local_style_property_setting_t*)local_style_p->style_property_settings;
    empty_style_property_setting_p = NULL;

    if (style_property_setting_p != NULL) {
        for (i = 0; i < local_style_p->style_property_setting_count; ++i) {
            if (empty_style_property_setting_p == NULL && style_property_setting_p->object_p == NULL) {
                empty_style_property_setting_p = style_property_setting_p;
            }
            if (style_property_setting_p->object_p == object_p && style_property_setting_p->selector == selector
                && style_property_setting_p->property == property) {
                return style_property_setting_p;
            }
            if (style_property_setting_p->next_p != NULL) 
                style_property_setting_p = (_ui_local_style_property_setting_t*)style_property_setting_p->next_p;
            else break;
        }
    }

    if (empty_style_property_setting_p == NULL) {
        empty_style_property_setting_p = (_ui_local_style_property_setting_t*)lv_mem_alloc(sizeof(_ui_local_style_property_setting_t));
        LV_ASSERT_MALLOC(empty_style_property_setting_p);
        if (empty_style_property_setting_p == NULL) return NULL;
        if (style_property_setting_p != NULL) style_property_setting_p->next_p = (void*)empty_style_property_setting_p;
        else local_style_p->style_property_settings = empty_style_property_setting_p;
        style_property_setting_p = empty_style_property_setting_p;
        style_property_setting_p->next_p = NULL;
        ++local_style_p->style_property_setting_count;
    }
    else style_property_setting_p = empty_style_property_setting_p;

    style_property_setting_p->object_p = object_p;
    lv_obj_add_event_cb(object_p, _ui_local_style_property_setting_delete, LV_EVENT_DELETE, &style_property_setting_p->object_p);
    style_property_setting_p->selector = selector;
    style_property_setting_p->property = property;
    return style_property_setting_p;
}

// --- FONCTIONS PUBLIQUES ---

void ui_object_set_themeable_style_property
(lv_obj_t* object_p, lv_style_selector_t selector, lv_style_prop_t property, const ui_theme_variable_t* theme_variable_p) {
    _ui_local_style_t* local_style_p;
    _ui_local_style_property_setting_t* property_setting_p;

    if (object_p == NULL || theme_variable_p == NULL) return;
    local_style_p = _ui_local_style_create(theme_variable_p, true);
    if (local_style_p == NULL) return;
    property_setting_p = _ui_local_style_property_setting_create(local_style_p, object_p, selector, property);
    if (property_setting_p == NULL) return;

    lv_obj_set_local_style_prop(object_p, property, _ui_style_value_convert(property, ui_get_theme_value(theme_variable_p)), selector);
}

void _ui_theme_set_variable_styles(uint8_t mode) {
    static uint8_t ui_theme_idx_previous = 255;
    uint32_t i, j;
    _ui_local_style_property_setting_t* property_setting_p;
    ui_style_variable_t style_value;
    ui_style_variable_t* style_variable_p;

    uint8_t ui_Theme_Changed = (ui_theme_idx != ui_theme_idx_previous);
    ui_theme_idx_previous = ui_theme_idx;

    for (i = 0; i < _ui_local_style_count; ++i) {
        style_variable_p = _ui_local_styles[i].style_variable_p;
        if (_ui_local_styles[i].is_themeable) style_value = ui_get_theme_value(style_variable_p);
        else style_value = *style_variable_p;

        if (style_variable_p != _ui_local_styles[i].previous_pointer || style_value != _ui_local_styles[i].previous_value
            || mode == UI_VARIABLE_STYLES_MODE_INIT || ui_Theme_Changed) {
            
            _ui_local_styles[i].previous_pointer = (void*)style_variable_p;
            _ui_local_styles[i].previous_value = style_value;

            property_setting_p = (_ui_local_style_property_setting_t*)_ui_local_styles[i].style_property_settings;
            for (j = 0; j < _ui_local_styles[i].style_property_setting_count; ++j) {
                if (property_setting_p && property_setting_p->object_p != NULL) {
                    ui_object_set_local_style_property(property_setting_p->object_p, property_setting_p->selector, property_setting_p->property, style_value);
                }
                if (property_setting_p && property_setting_p->next_p != NULL) 
                    property_setting_p = (_ui_local_style_property_setting_t*)property_setting_p->next_p;
                else break;
            }
        }
    }
}