// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#include "../ui.h"

void ui_event_comp_Slider1_Slider1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_Slider1 = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_LabelSliderLuminositeEcran, target, "", " %");
}
}

// COMPONENT Slider1

lv_obj_t *ui_Slider1_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Slider1;
cui_Slider1 = lv_slider_create(comp_parent);
lv_slider_set_value( cui_Slider1, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(cui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( cui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( cui_Slider1, 359);
lv_obj_set_height( cui_Slider1, 53);
lv_obj_set_x( cui_Slider1, -30 );
lv_obj_set_y( cui_Slider1, -41 );
lv_obj_set_align( cui_Slider1, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(cui_Slider1, lv_color_hex(0x2095F6), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Slider1, 150, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_Slider1, lv_color_hex(0x2095F6), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_Slider1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_Slider1, 100, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_Slider1, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Slider1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SLIDER1_NUM);
children[UI_COMP_SLIDER1_SLIDER1] = cui_Slider1;
lv_obj_add_event_cb(cui_Slider1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Slider1, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_Slider1, ui_event_comp_Slider1_Slider1, LV_EVENT_ALL, children);
ui_comp_Slider1_create_hook(cui_Slider1);
return cui_Slider1; 
}

