// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_HelloWorldBox = NULL;lv_obj_t *ui_HelloWorld = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HelloWorldBox = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_HelloWorldBox, 399);
lv_obj_set_height( ui_HelloWorldBox, 171);
lv_obj_set_align( ui_HelloWorldBox, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HelloWorldBox, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HelloWorldBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HelloWorldBox, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HelloWorld = lv_label_create(ui_HelloWorldBox);
lv_obj_set_width( ui_HelloWorld, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HelloWorld, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HelloWorld, LV_ALIGN_CENTER );
lv_label_set_text(ui_HelloWorld,"HELLO WORLD");
lv_obj_set_style_text_color(ui_HelloWorld, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HelloWorld, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HelloWorld, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_HelloWorldBox= NULL;
ui_HelloWorld= NULL;

}
