// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENCONFIG_H
#define UI_SCREENCONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenconfig
extern void ui_screenconfig_screen_init(void);
extern void ui_screenconfig_screen_destroy(void);
extern lv_obj_t *ui_screenconfig;
extern lv_obj_t *ui_bgscreenconfig;
extern void ui_event_blackledpanel1( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel1;
extern void ui_event_blackledpanel2( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel2;
extern void ui_event_blackledpanel3( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel3;
extern void ui_event_blackledpanel4( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel4;
extern void ui_event_blackledpanel5( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel5;
extern void ui_event_blackledpanel6( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel6;
extern void ui_event_blackledpanel7( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel7;
extern void ui_event_blackledpanel8( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel8;
extern void ui_event_greenledpanel( lv_event_t * e);
extern lv_obj_t *ui_greenledpanel;
extern void ui_event_orangeledpanel( lv_event_t * e);
extern lv_obj_t *ui_orangeledpanel;
extern void ui_event_redledpanel( lv_event_t * e);
extern lv_obj_t *ui_redledpanel;
extern void ui_event_cyanledpanel( lv_event_t * e);
extern lv_obj_t *ui_cyanledpanel;
extern void ui_event_blueledpanel( lv_event_t * e);
extern lv_obj_t *ui_blueledpanel;
extern lv_obj_t *ui_consolelabel;
extern void ui_event_key1( lv_event_t * e);
extern lv_obj_t *ui_key1;
extern void ui_event_key2( lv_event_t * e);
extern lv_obj_t *ui_key2;
extern void ui_event_key3( lv_event_t * e);
extern lv_obj_t *ui_key3;
extern void ui_event_key4( lv_event_t * e);
extern lv_obj_t *ui_key4;
extern void ui_event_key5( lv_event_t * e);
extern lv_obj_t *ui_key5;
extern void ui_event_key6( lv_event_t * e);
extern lv_obj_t *ui_key6;
extern void ui_event_key7( lv_event_t * e);
extern lv_obj_t *ui_key7;
extern void ui_event_key8( lv_event_t * e);
extern lv_obj_t *ui_key8;
extern void ui_event_key9( lv_event_t * e);
extern lv_obj_t *ui_key9;
extern void ui_event_keybackspace( lv_event_t * e);
extern lv_obj_t *ui_keybackspace;
extern void ui_event_key0( lv_event_t * e);
extern lv_obj_t *ui_key0;
extern void ui_event_keydot( lv_event_t * e);
extern lv_obj_t *ui_keydot;
// CUSTOM VARIABLES
extern lv_obj_t *uic_screenconfig;
extern lv_obj_t *uic_bgscreenconfig;
extern lv_obj_t *uic_blackledpanel1;
extern lv_obj_t *uic_blackledpanel2;
extern lv_obj_t *uic_greenledpanel;
extern lv_obj_t *uic_orangeledpanel;
extern lv_obj_t *uic_redledpanel;
extern lv_obj_t *uic_cyanledpanel;
extern lv_obj_t *uic_blueledpanel;
extern lv_obj_t *uic_consolelabel;
extern lv_obj_t *uic_key1;
extern lv_obj_t *uic_key2;
extern lv_obj_t *uic_key3;
extern lv_obj_t *uic_key4;
extern lv_obj_t *uic_key5;
extern lv_obj_t *uic_key6;
extern lv_obj_t *uic_key7;
extern lv_obj_t *uic_key8;
extern lv_obj_t *uic_keybackspace;
extern lv_obj_t *uic_key0;
extern lv_obj_t *uic_keydot;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

