// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#ifndef UI_SCREENMENU_H
#define UI_SCREENMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMenu
extern void ui_ScreenMenu_screen_init(void);
extern void ui_ScreenMenu_screen_destroy(void);
extern lv_obj_t *ui_ScreenMenu;
extern void ui_event_MenuDisplay1( lv_event_t * e);
extern lv_obj_t *ui_MenuDisplay1;
extern void ui_event_MenuConfig2( lv_event_t * e);
extern lv_obj_t *ui_MenuConfig2;
extern void ui_event_MenuLeds3( lv_event_t * e);
extern lv_obj_t *ui_MenuLeds3;
extern void ui_event_MenuRealTime4( lv_event_t * e);
extern lv_obj_t *ui_MenuRealTime4;
extern void ui_event_MenuDisplay5( lv_event_t * e);
extern lv_obj_t *ui_MenuDisplay5;
extern void ui_event_MenuConfig6( lv_event_t * e);
extern lv_obj_t *ui_MenuConfig6;
extern void ui_event_MenuLeds7( lv_event_t * e);
extern lv_obj_t *ui_MenuLeds7;
extern void ui_event_MenuRealTime8( lv_event_t * e);
extern lv_obj_t *ui_MenuRealTime8;
extern void ui_event_MenuDisplay9( lv_event_t * e);
extern lv_obj_t *ui_MenuDisplay9;
// CUSTOM VARIABLES
extern lv_obj_t *uic_MenuDisplay1;
extern lv_obj_t *uic_MenuConfig2;
extern lv_obj_t *uic_MenuLeds3;
extern lv_obj_t *uic_MenuRealTime4;
extern lv_obj_t *uic_MenuDisplay5;
extern lv_obj_t *uic_MenuConfig6;
extern lv_obj_t *uic_MenuLeds7;
extern lv_obj_t *uic_MenuRealTime8;
extern lv_obj_t *uic_MenuDisplay9;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

