// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_HelloWorldBox;
extern lv_obj_t *ui_HelloWorld;
extern void ui_event_sliderbrightness( lv_event_t * e);
extern lv_obj_t *ui_sliderbrightness;
// CUSTOM VARIABLES
extern lv_obj_t *uic_sliderbrightness;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

