// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: RT_Dash_70_waveshare_esp32-p4_V1

#ifndef UI_SCREENDISPLAYECU_H
#define UI_SCREENDISPLAYECU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenDisplayECU
extern void ui_ScreenDisplayECU_screen_init(void);
extern void ui_ScreenDisplayECU_screen_destroy(void);
extern void ui_event_ScreenDisplayECU( lv_event_t * e);
extern lv_obj_t *ui_ScreenDisplayECU;
extern void ui_event_ButtonHome1( lv_event_t * e);
extern lv_obj_t *ui_ButtonHome1;
extern lv_obj_t *ui_ContainerECU;
extern lv_obj_t *ui_LabelCANBUS;
extern lv_obj_t *ui_LabelChoixECU;
extern lv_obj_t *ui_PanelECU;
extern lv_obj_t *ui_PanelChoixECU;
extern void ui_event_Switch1( lv_event_t * e);
extern lv_obj_t *ui_Switch1;
extern void ui_event_Switch2( lv_event_t * e);
extern lv_obj_t *ui_Switch2;
extern void ui_event_Switch3( lv_event_t * e);
extern lv_obj_t *ui_Switch3;
extern void ui_event_Switch4( lv_event_t * e);
extern lv_obj_t *ui_Switch4;
extern void ui_event_Switch5( lv_event_t * e);
extern lv_obj_t *ui_Switch5;
extern lv_obj_t *ui_PanelTextECU;
extern lv_obj_t *ui_LabelMaxxECU;
extern lv_obj_t *ui_LabelKMS;
extern lv_obj_t *ui_LabelERACE;
extern lv_obj_t *ui_LabelECUMASTER;
extern lv_obj_t *ui_LabelLINK;
extern lv_obj_t *ui_ContainerLuminosite;
extern lv_obj_t *ui_LabelLuminositeDash;
extern lv_obj_t *ui_LabelLuminositeLEDs;
extern void ui_event_SliderLuminositeEcran( lv_event_t * e);
extern lv_obj_t *ui_SliderLuminositeEcran;
extern lv_obj_t *ui_LabelSliderLuminositeEcran;
extern void ui_event_SliderLuminositeLEDs( lv_event_t * e);
extern lv_obj_t *ui_SliderLuminositeLEDs;
extern lv_obj_t *ui_LabelSliderLuminositeLEDs;
extern lv_obj_t *ui_ContainerReglageHeure;
extern lv_obj_t *ui_LabelReglageHeure;
extern lv_obj_t *ui_Horloge3;
extern lv_obj_t *ui_LabelHeure3;
extern lv_obj_t *ui_LabelSepHeureMin3;
extern lv_obj_t *ui_LabelMin3;
extern lv_obj_t *ui_RollerHeure;
extern lv_obj_t *ui_RollerMinute;
extern lv_obj_t *ui_ContainerAffichageBV;
extern lv_obj_t *ui_SwitchBV;
extern lv_obj_t *ui_LabelAffichageBV;
extern lv_obj_t *ui_ContainerZoneRouge;
extern lv_obj_t *ui_LabelZoneRouge;
extern void ui_event_SliderRPMZoneRouge( lv_event_t * e);
extern lv_obj_t *ui_SliderRPMZoneRouge;
extern lv_obj_t *ui_LabelSliderRPMZoneRouge;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ButtonHome1;
extern lv_obj_t *uic_ContainerECU;
extern lv_obj_t *uic_LabelCANBUS;
extern lv_obj_t *uic_LabelChoixECU;
extern lv_obj_t *uic_PanelECU;
extern lv_obj_t *uic_PanelChoixECU;
extern lv_obj_t *uic_Switch1;
extern lv_obj_t *uic_Switch2;
extern lv_obj_t *uic_Switch3;
extern lv_obj_t *uic_Switch4;
extern lv_obj_t *uic_Switch5;
extern lv_obj_t *uic_PanelTextECU;
extern lv_obj_t *uic_LabelMaxxECU;
extern lv_obj_t *uic_LabelKMS;
extern lv_obj_t *uic_LabelERACE;
extern lv_obj_t *uic_LabelECUMASTER;
extern lv_obj_t *uic_LabelLINK;
extern lv_obj_t *uic_ContainerLuminosite;
extern lv_obj_t *uic_LabelLuminositeDash;
extern lv_obj_t *uic_LabelLuminositeLEDs;
extern lv_obj_t *uic_SliderLuminositeEcran;
extern lv_obj_t *uic_LabelSliderLuminositeEcran;
extern lv_obj_t *uic_SliderLuminositeLEDs;
extern lv_obj_t *uic_LabelSliderLuminositeLEDs;
extern lv_obj_t *uic_ContainerReglageHeure;
extern lv_obj_t *uic_LabelReglageHeure;
extern lv_obj_t *uic_Horloge3;
extern lv_obj_t *uic_LabelHeure3;
extern lv_obj_t *uic_LabelSepHeureMin3;
extern lv_obj_t *uic_LabelMin3;
extern lv_obj_t *uic_RollerHeure;
extern lv_obj_t *uic_RollerMinute;
extern lv_obj_t *uic_ContainerAffichageBV;
extern lv_obj_t *uic_SwitchBV;
extern lv_obj_t *uic_LabelAffichageBV;
extern lv_obj_t *uic_ContainerZoneRouge;
extern lv_obj_t *uic_LabelZoneRouge;
extern lv_obj_t *uic_SliderRPMZoneRouge;
extern lv_obj_t *uic_LabelSliderRPMZoneRouge;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

