// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *uic_sliderbrightness;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_HelloWorldBox = NULL;lv_obj_t *ui_HelloWorld = NULL;lv_obj_t *ui_sliderbrightness = NULL;
// event funtions
void ui_event_sliderbrightness( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      brightness_slider_event_cb( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);

ui_HelloWorldBox = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_HelloWorldBox, 399);
lv_obj_set_height( ui_HelloWorldBox, 171);
lv_obj_set_align( ui_HelloWorldBox, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HelloWorldBox, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HelloWorldBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HelloWorldBox, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HelloWorld = lv_label_create(ui_HelloWorldBox);
lv_obj_set_width( ui_HelloWorld, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HelloWorld, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HelloWorld, LV_ALIGN_CENTER );
lv_label_set_text(ui_HelloWorld,"HELLO WORLD");
lv_obj_set_style_text_color(ui_HelloWorld, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HelloWorld, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HelloWorld, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sliderbrightness = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_sliderbrightness, 100, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_sliderbrightness)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_sliderbrightness, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_sliderbrightness, 500);
lv_obj_set_height( ui_sliderbrightness, 15);
lv_obj_set_x( ui_sliderbrightness, 1 );
lv_obj_set_y( ui_sliderbrightness, -232 );
lv_obj_set_align( ui_sliderbrightness, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_sliderbrightness, lv_color_hex(0xDFDBDB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sliderbrightness, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_sliderbrightness, lv_color_hex(0xFF5E00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sliderbrightness, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_sliderbrightness, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_sliderbrightness, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_sliderbrightness, 19, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_sliderbrightness, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_sliderbrightness, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_sliderbrightness, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_sliderbrightness, lv_color_hex(0xFF8C00), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sliderbrightness, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_sliderbrightness, lv_color_hex(0xF8EBEB), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_sliderbrightness, LV_GRAD_DIR_HOR, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_sliderbrightness, ui_event_sliderbrightness, LV_EVENT_ALL, NULL);
uic_sliderbrightness = ui_sliderbrightness;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_HelloWorldBox= NULL;
ui_HelloWorld= NULL;
uic_sliderbrightness= NULL;
ui_sliderbrightness= NULL;

}
