// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENCONFIG_H
#define UI_SCREENCONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenconfig
extern void ui_screenconfig_screen_init(void);
extern void ui_screenconfig_screen_destroy(void);
extern lv_obj_t *ui_screenconfig;
extern lv_obj_t *ui_bgscreenconfig;
extern void ui_event_blackledpanel1( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel1;
extern void ui_event_blackledpanel2( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel2;
extern void ui_event_blackledpanel3( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel3;
extern void ui_event_blackledpanel4( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel4;
extern void ui_event_blackledpanel5( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel5;
extern void ui_event_greenledpanel( lv_event_t * e);
extern lv_obj_t *ui_greenledpanel;
extern void ui_event_blackledpanel6( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel6;
extern void ui_event_blackledpanel7( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel7;
extern void ui_event_orangeledpanel( lv_event_t * e);
extern lv_obj_t *ui_orangeledpanel;
extern void ui_event_blackledpanel8( lv_event_t * e);
extern lv_obj_t *ui_blackledpanel8;
extern void ui_event_redledpanel( lv_event_t * e);
extern lv_obj_t *ui_redledpanel;
extern void ui_event_cyanledpanel( lv_event_t * e);
extern lv_obj_t *ui_cyanledpanel;
extern void ui_event_blueledpanel( lv_event_t * e);
extern lv_obj_t *ui_blueledpanel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_screenconfig;
extern lv_obj_t *uic_blackledpanel1;
extern lv_obj_t *uic_blackledpanel2;
extern lv_obj_t *uic_greenledpanel;
extern lv_obj_t *uic_orangeledpanel;
extern lv_obj_t *uic_redledpanel;
extern lv_obj_t *uic_cyanledpanel;
extern lv_obj_t *uic_blueledpanel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

